using System;

namespace PryCjTelecom.ENTIDAD
{
    public class DbOperacionesCj
    {
        public string OT { get; set; }
        public DateTime? FechaInicio { get; set; }
        public int? IdZona { get; set; }
        public string? IdSite { get; set; }
        public decimal? CorreSite { get; set; }
        public int? Status_Claro { get; set; }
        public int? IdDepartamento { get; set; }
        public string? IdFarEnd { get; set; }
        public int? IdTransmision { get; set; }
        public int? IdProyecto { get; set; }
        public int? IdTorrera { get; set; }
        public int? IdTipoTorre { get; set; }
        public decimal? Altura { get; set; }
        public int? CantSect { get; set; }
        public DateTime? LPE { get; set; }
        public int? IdOnAir { get; set; }
        public int? IdActaCob { get; set; }
        public int? IdCapitalizacion { get; set; }
        public string? NroOc { get; set; }
        public decimal? MontoCw { get; set; }
        public decimal? MontoEnergia { get; set; }
        public decimal? MontoPext { get; set; }
        public decimal? MontoTi { get; set; }
        public decimal? Monto { get; set; }
        public string? Latitud { get; set; }
        public string? Longitud { get; set; }
        public string? Direccion { get; set; }
        public int? IdCandado { get; set; }
        public int? IdContacto { get; set; }
        public string? Telefono { get; set; }
        public int? IdStatusIng { get; set; }
        public int? GIS_INGENIERIA { get; set; }
        public int? DATA_ING_TX_CLARO { get; set; }
        public DateTime? F_DATA_ING_SOL_TX { get; set; }
        public int? DIAS_DATA { get; set; }
        public DateTime? F_DATA_ING_RX { get; set; }
        public int? HILOS_ASIG { get; set; }
        public DateTime? F_SOL_ASIG_HILOS { get; set; }
        public DateTime? F_RX_ASIG_HILOS { get; set; }
        public string? ID_FAREND { get; set; }
        public int? AnalistaIng { get; set; }
        public int? NroHilos { get; set; }
        public int? idContrataResp { get; set; }
        public DateTime? FecAsigCon { get; set; }
        public DateTime? F_LEV_CAMPO { get; set; }
        public int? KMZ { get; set; }
        public int? REP_FOT_DISEno { get; set; }
        public int? IdPlanosPdf { get; set; }
        public int? IdDiagramaEmpalme { get; set; }
        public int? PptoDise { get; set; }
        public DateTime? fecDisenoPext { get; set; }
        public int? TIEMPO_SIN_VAL { get; set; }
        public DateTime? FecDisenoPextValidado { get; set; }
        public int? Status_Diseno { get; set; }
        public string? OBSERVACIONES { get; set; }
        public decimal? metradoDiseno { get; set; }
        public decimal? MetradoExistente { get; set; }
        public int? ESTATUS_OC { get; set; }
        public int? IdIngDinamica { get; set; }
        public int? PreInt { get; set; }
        public int? RED_FLAG_PROVIAS { get; set; }
        public string? SolucionEmerg { get; set; }
        public decimal? PotenciaKw { get; set; }
        public decimal? PorcenCw { get; set; }
        public decimal? PorcenEnergia { get; set; }
        public decimal? PorcenPext { get; set; }
        public decimal? PorcenTi { get; set; }
        public DateTime? FechaPext { get; set; }
        public int? StatusPext { get; set; }
        public int? PriPext { get; set; }
        public decimal? M_FO_EXISTENTE { get; set; }
        public decimal? M_FO_PROYECTADO { get; set; }
        public int? StatusCartaPoste { get; set; }
        public DateTime? F_SOL_CARTA { get; set; }
        public string? NroPostesProy { get; set; }
        public int? NroPostesExBt { get; set; }
        public int? NroPostesExAmov { get; set; }
        public int? NroPostesExMt { get; set; }
        public int? TotalPostesElec { get; set; }
        public int? TotalPostes { get; set; }
        public int? CONCESIONARIA { get; set; }
        public int? StatusExpPext { get; set; }
        public int? IdStatusElectrica { get; set; }
        public string? NroExpediente { get; set; }
        public DateTime? FecIngExpediente { get; set; }
        public int? IdJefeConcesionaria { get; set; }
        public int? IdGestorZonal { get; set; }
        public int? ESTATUS_INSPECCION { get; set; }
        public DateTime? FecInsp { get; set; }
        public int? IdRespGestion { get; set; }
        public int? PostesObs { get; set; }
        public int? POSTES_FCC_VAL { get; set; }
        public int? F_VAL_FCC { get; set; }
        public int? IdExpMun { get; set; }
        public int? MUNICIPALIDAD { get; set; }
        public DateTime? fecIngMuni { get; set; }
        public int? FUIIT { get; set; }
        public string? ComenExpMun { get; set; }
        public int? PMA { get; set; }
        public int? CIRA { get; set; }
        public int? PROVIAS { get; set; }
        public int? EVAP { get; set; }
        public int? SERVIDUMBRE { get; set; }
        public int? StatPermEspe { get; set; }
        public int? PermEspecial { get; set; }
        public DateTime? F_FUIIT { get; set; }
        public DateTime? F_PMA { get; set; }
        public DateTime? F_CIRA { get; set; }
        public DateTime? F_PROVIAS { get; set; }
        public DateTime? F_EVAP { get; set; }
        public DateTime? F_SERVIDUMBRE { get; set; }
        public DateTime? FC_Licencia { get; set; }
        public int? Licencia { get; set; }
        public DateTime? Fin_Licencia { get; set; }
        public int? DiasVenc { get; set; }
        public int? StatusEjecCw { get; set; }
        public string? RedFlagCw { get; set; }
        public int? TipoPoste { get; set; }
        public int? AlturaPoste { get; set; }
        public int? StatusPoste { get; set; }
        public DateTime? FecPoste { get; set; }
        public int? TrasladoPoste { get; set; }
        public DateTime? FecTraslado { get; set; }
        public int? CwPreliminar { get; set; }
        public DateTime? FechaCw { get; set; }
        public int? Parres { get; set; }
        public DateTime? FecParres { get; set; }
        public int? Pararrayos { get; set; }
        public DateTime? FecPararayos { get; set; }
        public int? FcProyecto { get; set; }
        public string? CWTS { get; set; }
        public DateTime? Inicio_CW { get; set; }
        public DateTime? Fi_CW { get; set; }
        public int? StatusEjecTi { get; set; }
        public string? RED_FLAG_TI { get; set; }
        public int? Tecnologia { get; set; }
        public int? ModAntena { get; set; }
        public int? CantSectores { get; set; }
        public int? Tipo { get; set; }
        public int? EstHwTi { get; set; }
        public DateTime? F_SOL_RF { get; set; }
        public DateTime? F_ASIG_RF { get; set; }
        public DateTime? F_PAP_RF { get; set; }
        public DateTime? F_RX_RF { get; set; }
        public int? NroDiasRf { get; set; }
        public int? Df { get; set; }
        public int? WOTX { get; set; }
        public int? SCRIPT { get; set; }
        public int? FO_PINT { get; set; }
        public int? SOPORTES_RF { get; set; }
        public int? CONTRATA_TI { get; set; }
        public DateTime? F_ACT_REAL { get; set; }
        public int? W_ACT_REAL { get; set; }
        public int? PtaServ { get; set; }
        public int? EnvActCob { get; set; }
        public DateTime? FecActCob { get; set; }
        public int? Capitalizacion { get; set; }
        public int? PRIORIDAD_TI { get; set; }
        public string? SEGUIMIENTO_TI { get; set; }
        public int? StatusEnergia { get; set; }
        public string? RedCw { get; set; }
        public int? CONCESIONARIAS { get; set; }
        public decimal? TARIFA_REQUERIDA { get; set; }
        public decimal? PotenciaReq { get; set; }
        public decimal? PotContratada { get; set; }
        public int? IdGestorEne { get; set; }
        public int? IdLocalidad { get; set; }
        public int? EstExpMunPal { get; set; }
        public DateTime? FecIngExpAc { get; set; }
        public int? tTransMuniAc { get; set; }
        public string? COMENTARIOS { get; set; }
        public string? ExpElec { get; set; }
        public string? NroAtencion { get; set; }
        public DateTime? FecIngExp { get; set; }
        public int? tTrans { get; set; }
        public int? idFact { get; set; }
        public DateTime? fecFact { get; set; }
        public int? diasFact { get; set; }
        public int? MureteAdec { get; set; }
        public DateTime? F_MURETE { get; set; }
        public decimal? MetrajeProy { get; set; }
        public int? NroPostesproy1 { get; set; }
        public int? IdPresupuestado { get; set; }
        public int? IdContrato { get; set; }
        public int? IdSuministro { get; set; }
        public int? IdTablero { get; set; }
        public DateTime? Fc_energizado { get; set; }
        public DateTime? FcEneProv { get; set; }
        public DateTime? FecIniEnergia { get; set; }
        public DateTime? FinFecEneriga { get; set; }
        public string? ComentariosAC { get; set; }
        public string? W01 { get; set; }
        public string? W02 { get; set; }
        public string? W03 { get; set; }
        public string? W04 { get; set; }
        public string? W05 { get; set; }
        public string? W06 { get; set; }
        public string? W07 { get; set; }
        public string? W08 { get; set; }
        public string? W09 { get; set; }
        public string? W10 { get; set; }
        public string? W11 { get; set; }
        public string? W12 { get; set; }
        public string? W13 { get; set; }
        public string? W14 { get; set; }
        public string? W15 { get; set; }
        public string? W16 { get; set; }
        public string? W17 { get; set; }
        public string? W18 { get; set; }
        public string? W19 { get; set; }
        public string? W20 { get; set; }
        public string? W21 { get; set; }
        public string? W22 { get; set; }
        public string? W23 { get; set; }
        public string? W24 { get; set; }
        public string? W25 { get; set; }
        public string? W26 { get; set; }
        public string? W27 { get; set; }
        public string? W28 { get; set; }
        public string? W29 { get; set; }
        public string? W30 { get; set; }
        public int? StatusEjecPext { get; set; }
        public string? redFlagPext { get; set; }
        public int? IdStatusPext { get; set; }
        public int? Viabilidad { get; set; }
        public int? ESTADO_HW { get; set; }
        public DateTime? F_SOL_FO { get; set; }
        public DateTime? F_ASIG_FO { get; set; }
        public DateTime? F_PAP_FO { get; set; }
        public DateTime? F_RX_FO { get; set; }
        public int? NroEntFo { get; set; }
        public int? COD_POSTE { get; set; }
        public int? STATUS_DATA_PEXT { get; set; }
        public int? PosFib09 { get; set; }
        public int? PosFib11 { get; set; }
        public int? ESTATUS_POSTES_FV { get; set; }
        public int? PosCac09 { get; set; }
        public int? PosCac11 { get; set; }
        public int? StatusPostesCac { get; set; }
        public int? TotalPostesFinal { get; set; }
        public int? StatusPostesgral { get; set; }
        public int? AnalistaPext { get; set; }
        public int? CONTRATA_PEXT { get; set; }
        public DateTime? F_INIC_EJEC { get; set; }
        public DateTime? F_FIN_PEXT { get; set; }
        public int? W_PEXT_EJEC { get; set; }
        public int? POSTES { get; set; }
        public int? TENDIDO { get; set; }
        public int? FUSIONES { get; set; }
        public int? PINT { get; set; }
        public int? ACABADOS { get; set; }
        public int? NroHilosInstalados { get; set; }
        public decimal? MetrajeInstal { get; set; }
        public int? Prioridad { get; set; }
        public string? SegPext { get; set; }
        public int? StatusEjecucionTi { get; set; }
        public string? RedFlgTi { get; set; }
        public DateTime? FecAct { get; set; }
        public int? W_ACT { get; set; }
        public int? IdProyecto1 { get; set; }
        public int? PrioridadClaro { get; set; }
        public int? Ot_Pap2 { get; set; }
        public string? usuarioCreacion { get; set; }
        public DateTime? fechaCreacion { get; set; }
        public int? IdEstado { get; set; }
        public int? OPE_STAT_INGE_PEXT { get; set; }
        public int? Status_Cj { get; set; }
        public int? IdCliente { get; set; }
    }
}
