namespace PryCjTelecom.ENTIDAD
{
    public class DetGalvanizado
    {
        public int IdCliente { get; set; }
        public int IdProyecto { get; set; }
        public string IdSite { get; set; }
        public decimal CorreSite { get; set; }
        public string TipoTrabajo { get; set; }
        public string PedidoSap { get; set; }
        public string NroGalvanizado { get; set; }
        public string Posicion { get; set; }
        public string Correlativo { get; set; }
        public string? Serie { get; set; }
        public string? CodPap { get; set; }
        public decimal? CantSap { get; set; }
        public string? Centro { get; set; }
        public string? Almacen { get; set; }
        public string? Lote { get; set; }
        public string? Usuario { get; set; }
        public DateTime? Fecha { get; set; }
        public DateTime? Hora { get; set; }
        public int? IdEstado { get; set; }
        public string? Observacion { get; set; }
        public string? Comentario { get; set; }
        public int? LinReg { get; set; }
        public int? NroEnvio { get; set; }
        public int? IdClienteOrigen { get; set; }
        public int? IdProyectoOrigen { get; set; }
        public string? IdSiteOrigen { get; set; }
        public decimal? CorreSiteOrigen { get; set; }
        public string? TipoTrabajoOrigen { get; set; }
        public string? RutaImagen { get; set; }
        public bool? IdDespacho { get; set; }
        public string? ComenEnvio { get; set; }
        public DateTime? FechaEnvio { get; set; }
        public DateTime? HoraEnvio { get; set; }
        public string? NroGuia { get; set; }
        public int? IdAgencia { get; set; }
        public decimal? MontoEnvio { get; set; }
        public int? IdRespEnvio { get; set; }
        public DateTime? FechaEntrega { get; set; }
        public DateTime? FechaEnviado { get; set; }
        public int? Aplica { get; set; }
        public DateTime? FechaRecojo { get; set; }
        public string? ImagenEnvio { get; set; }
        public int? IdUbicacion { get; set; }
        public int? IdRespCampo { get; set; }
        public DateTime? FechaCampo { get; set; }
        public string? UsuarioMod { get; set; }
        public DateTime? FechaAprobar { get; set; }
        public int? IdRespAprobar { get; set; }
        public DateTime? FechaDespacho { get; set; }
        public int? IdRespDespacho { get; set; }
        public DateTime? FechaSolicitud { get; set; }
        public int? IdRespSolicitud { get; set; }
        public string? ImagenSolicitud { get; set; }
        public int? IdRespRecojo { get; set; }
        public DateTime? FechaCierre { get; set; }
        public int? IdRespCierre { get; set; }
        public string? UsuarioCreacion { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public string? ImagenCierre { get; set; }
        public int? IdRespObs { get; set; }
        public int? IdRespRec { get; set; }
        public DateTime? FechaRechazar { get; set; }
        public DateTime? FechaObs { get; set; }
        public string? RutaDesImagen { get; set; }
        public int? NroCierre { get; set; }
        public string? NumeroCierre { get; set; }
        public decimal? CantDesp { get; set; }
        public DateTime? FechaCruce { get; set; }
        public int? IdRespCruce { get; set; }
        public decimal? CantEnvio { get; set; }
        public decimal? CantCampo { get; set; }
        public decimal? CantCruce { get; set; }
        public decimal? CantCierre { get; set; }
        public decimal? CantFolio { get; set; }
        public string? NroFolio { get; set; }
        public string? NroOc { get; set; }
        public string? NroPosicion { get; set; }
        public DateTime? FechaTermino { get; set; }
        public int? IdRespTermino { get; set; }
        public int? IdBloqueo { get; set; }
        public string? NroGuiaRetorno { get; set; }
        public int? IdAgenciaRetorno { get; set; }
        public string? Region { get; set; }
        public string? PosicionLog { get; set; }
        public string? RutaPre { get; set; }
        public int? IdRespReq { get; set; }
        public DateTime? FechaReq { get; set; }
        public int? IdRespCompra { get; set; }
        public DateTime? FechaCompra { get; set; }
        public int? IdRespFab { get; set; }
        public DateTime? FechaFab { get; set; }
        public int? IdRespGal { get; set; }
        public DateTime? FechaGal { get; set; }
        public int? IdocRel { get; set; }
        public decimal? CorrelativoRel { get; set; }
        public int? IdSub { get; set; }
        public string? RutaSolicitud { get; set; }
        public int? IdEstadoStock { get; set; }
        public DateTime? FechaFinFab { get; set; }
        public int? IdEstadoFab { get; set; }
        public decimal? PesoDet { get; set; }
        public string? NroSolicitud { get; set; }
    }
}
