namespace PryCjTelecom.ENTIDAD
{
    public class DetImportar
    {
        public string? OcPos { get; set; }
        public string? OT { get; set; }
        public string? PAP { get; set; }
        public string? IdSite { get; set; }
        public int? Correlativo { get; set; }
        public string? IdTipoTrabajo { get; set; }
        public string? IdWork { get; set; }
        public int? IdProyecto { get; set; }
        public int? IdZona { get; set; }
        public string? IdEmpleado { get; set; }
        public string? FecAsignacion { get; set; }
        public string? MES { get; set; }
        public string? ANO { get; set; }
        public string? Estado_OC { get; set; }
        public string? Nro_Oc { get; set; }
        public string? Posicion { get; set; }
        public string? FechaOc { get; set; }
        public decimal? MontoOc { get; set; }
        public decimal? MontoLiq { get; set; }
        public decimal? LiqPap { get; set; }
        public string? ESTADO_EA { get; set; }
        public string? FechaEa { get; set; }
        public string? TIEMPO_EA { get; set; }
        public string? ANTIG_EA { get; set; }
        public string? CENFILE { get; set; }
        public string? STATUS_GIS { get; set; }
        public string? Status_Atp { get; set; }
        public int? Status_Folio { get; set; }
        public string? Comentarios { get; set; }
        public int? EA { get; set; }
        public string? GIS_SMW { get; set; }
        public string? STATUS_PAP { get; set; }
        public string? Status_Fact { get; set; }
        public string? Mes2 { get; set; }
        public string? Status_Cj { get; set; }
        public string? MesActivacion { get; set; }
        public string? FecActivaPap { get; set; }
        public string? FecActivaF { get; set; }
        public string? Status_Gerencia { get; set; }
        public string? Gerencia2 { get; set; }
        public string? ESTING { get; set; }
        public string? PLANO { get; set; }
        public string? VALMET { get; set; }
        public string? STATUS_CW { get; set; }
        public string? STATUS_RINI { get; set; }
        public string? StatusClaroMod { get; set; }
        public string? FecActMod { get; set; }
        public string? LiqMod { get; set; }
        public string? FolioMod { get; set; }
        public string? Status_Claro { get; set; }
        public string? F_act_Real { get; set; }
        public string? FOLIO_DENSI { get; set; }
        public string? LIQ_DENSI { get; set; }
        public string? Status_Ro { get; set; }
        public string? Liquidacion { get; set; }
        public string? Ivan { get; set; }
        public string? Site { get; set; }
        public string? TipoTrabajo { get; set; }
        public string? Work { get; set; }
        public string? Proyecto { get; set; }
        public string? Zona { get; set; }
        public string? Empleado { get; set; }
        public string? Folio { get; set; }
        public string? EaTxt { get; set; }
        public string? FechaActivacion { get; set; }
        public string? Folio_Ro { get; set; }
        public string? Corte { get; set; }
        public string? Facturado { get; set; }
        public int? IdCliente { get; set; }
        public string? Cliente { get; set; }
        public string? Pext_Ro { get; set; }
        public string? Folio_Roll_Pext { get; set; }
        public string? Pext_densi { get; set; }
        public string? Folio_densi_pext { get; set; }
        public decimal? NroInterno { get; set; }
        public int? IdEstado { get; set; }
        public decimal? AnoGestion { get; set; }
        public int? IdStatusClaro { get; set; }
        public int? IdActualizar { get; set; }
        public string? StatusOt { get; set; }
        public string? StatusOt2 { get; set; }
        public int? IdStatusOt { get; set; }
        public int? IdStatusOt2 { get; set; }
        public string? Folio2 { get; set; }
        public int? IdFolio2 { get; set; }
        public string? Capitalizacion { get; set; }
        public int? IdStatusCj { get; set; }
        public string? ATP { get; set; }
        public string? PrePasivo { get; set; }
    }
}
