namespace PryCjTelecom.ENTIDAD
{
    public class Planilla
    {
        public int IdProyecto { get; set; }
        public string IdSite { get; set; }
        public int IdTipoTrabajo { get; set; }
        public int IdTarea { get; set; }
        public decimal Correlativo { get; set; }
        public string? FecIngreso { get; set; }
        public string? Detalle { get; set; }
        public int? IdResponsable { get; set; }
        public int IdCliente { get; set; }
        public int? IdBien { get; set; }
        public int? IdComprobante { get; set; }
        public string? RUC { get; set; }
        public string? Serie { get; set; }
        public int? IdTipoPago { get; set; }
        public string? FecEmision { get; set; }
        public int? TipoMoneda { get; set; }
        public decimal? Total { get; set; }
        public decimal? Subtotal { get; set; }
        public decimal? IGV { get; set; }
        public int? IdRendicion { get; set; }
        public string? Observacion { get; set; }
        public string? Comentario { get; set; }
        public int? IdSolicitante { get; set; }
        public int? IdGestor { get; set; }
        public int? IdValidador { get; set; }
        public int? IdEjecutor { get; set; }
        public int? IdTransferencia { get; set; }
        public int? IdBanco { get; set; }
        public int? IdMoneda2 { get; set; }
        public int? IdRendir { get; set; }
        public string? FechaDeposito { get; set; }
        public int? IdRetencion { get; set; }
        public string? Otro { get; set; }
        public string? Otro2 { get; set; }
        public string? Otro3 { get; set; }
        public string? Otro4 { get; set; }
        public int? Estado { get; set; }
        public int? CorreSite { get; set; }
        public string? FechaPropuesta { get; set; }
        public int? IdBancoCta { get; set; }
        public string? Cuenta { get; set; }
        public string? CuentaInter { get; set; }
        public string? NombreCta { get; set; }
        public string? NombreProyecto { get; set; }
        public string? Site { get; set; }
        public string? Tipo_Trabajo { get; set; }
        public string? Tarea { get; set; }
        public string? Responsable { get; set; }
        public string? Cliente { get; set; }
        public string? Bien { get; set; }
        public string? Comprobante { get; set; }
        public string? Pago { get; set; }
        public string? Moneda { get; set; }
        public string? Rendicion { get; set; }
        public string? Solicitante { get; set; }
        public string? Gestor { get; set; }
        public string? Validador { get; set; }
        public string? Ejecutor { get; set; }
        public string? Transferencia { get; set; }
        public string? Banco { get; set; }
        public string? Moneda2 { get; set; }
        public string? Rendir { get; set; }
        public string? Retencion { get; set; }
        public string? FechaAprobador { get; set; }
        public string? Usuario { get; set; }
        public string? FechaCreacion { get; set; }
        public string? HoraCreacion { get; set; }
        public string? Ot { get; set; }
        public string? TipoPago { get; set; }
        public decimal? TipoCambio { get; set; }
        public string? NroFactura { get; set; }
        public bool? IdUrgente { get; set; }
        public int? IdReAprobador { get; set; }
        public DateTime? FechaReAprobador { get; set; }
        public int? IdOc { get; set; }
        public int? Fila { get; set; }
        public int? IdTipoDoc { get; set; }
        public string? ImgSustento { get; set; }
        public string? ImgFactura { get; set; }
        public int? IdUsuarioFactura { get; set; }
        public DateTime? FecImaFactura { get; set; }
        public string? NroOperacion { get; set; }
        public string? Cheque { get; set; }
        public int? IdAnticipo { get; set; }
        public string? MacAprobador { get; set; }
        public string? MacReAprobador { get; set; }
        public DateTime? FechaRevision { get; set; }
        public string? RevisionPm { get; set; }
        public string? RevisionPmAprobar { get; set; }
        public DateTime? FechaRevisionAprobar { get; set; }
        public decimal? MontoRetencion { get; set; }
    }
}
