namespace PryCjTelecom.ENTIDAD
{
    public class PROYECTOS_COMPLETOS
    {
        public string? OT { get; set; }
        public string? ZONA { get; set; }
        public string? ID_SITE { get; set; }
        public string? SITE_NAME { get; set; }
        public string? ESTATUS_CLARO { get; set; }
        public string? DEPARTAMENTO { get; set; }
        public string? FAR_END { get; set; }
        public string? TRANSM_ { get; set; }
        public string? PROYECTO { get; set; }
        public string? TORRERA { get; set; }
        public string? TIPO_TORRE { get; set; }
        public string? ALTURA { get; set; }
        public string? CANTIDAD_SECTORES { get; set; }
        public string? LPE { get; set; }
        public string? ON_AIR { get; set; }
        public string? ACTA_COBERT_ { get; set; }
        public string? CAPITALIZACION { get; set; }
        public string? N_OC { get; set; }
        public string? MONTO_S_CW { get; set; }
        public string? MONTO_S_ENERGIA { get; set; }
        public string? MONTO_S_PEXT { get; set; }
        public string? MONTO_S_TI { get; set; }
        public string? MONTO_S_ { get; set; }
        public string? DATOS { get; set; }
        public string? LATITUD { get; set; }
        public string? LONGITUD { get; set; }
        public string? DIRECCION { get; set; }
        public string? CAND_VALIDADO { get; set; }
        public string? CONTACTO { get; set; }
        public string? TELF_ { get; set; }
        public string? INGENIERÍA { get; set; }
        public string? PRIORIDAD_ING { get; set; }
        public string? PRIORIDAD_IMP { get; set; }
        public string? ESTATUS_INGENIERIA_PEXT { get; set; }
        public string? GIS_INGENIERIA { get; set; }
        public string? DATA_ING_TX_CLARO { get; set; }
        public string? PEXT { get; set; }
        public string? DIAS_DATA { get; set; }
        public string? F_DATA_ING_RX { get; set; }
        public string? HILOS_ASIG { get; set; }
        public string? F_SOL_ASIG_HILOS { get; set; }
        public string? F_RX_ASIG_HILOS { get; set; }
        public string? ID_FAREND { get; set; }
        public string? FAREND_SITE_NAME { get; set; }
        public string? CJ_ING_RESPONSABLE { get; set; }
        public string? _DE_HILOS_HABILITAR { get; set; }
        public string? PRE_DISEÑO { get; set; }
        public string? CONTRATA_RESP_DISEÑO { get; set; }
        public string? F_ASIG_INICIO__DISEÑO_CONTRATA { get; set; }
        public string? F_LEV_CAMPO { get; set; }
        public string? KMZ { get; set; }
        public string? REP_FOT_DISEÑO { get; set; }
        public string? PLANOS_PDF_CAD { get; set; }
        public string? DIAGRAMA_DE_EMPALME { get; set; }
        public string? REV_DISEÑO_CJ { get; set; }
        public string? PPTO_DISEÑO { get; set; }
        public string? F_DISEÑO_PEXT_ENVIADO { get; set; }
        public string? TIEMPO_SIN_VAL { get; set; }
        public string? F_DISEÑO_PEXT_VALIDADO { get; set; }
        public string? ESTATUS_DISEÑO { get; set; }
        public string? OBSERVACIONES { get; set; }
        public string? METRADO_DISEÑO { get; set; }
        public string? METRADO_EXISTENTE { get; set; }
        public string? COD_SAP { get; set; }
        public string? DESCRIPCIÓN { get; set; }
        public string? TIPO_SPAM { get; set; }
        public string? SOT_CID_PROY { get; set; }
        public string? ESTATUS_OC { get; set; }
        public string? INGENIERIA_DINAMICA { get; set; }
        public string? ESTATUS_PRESUPUESTO_INTEGRAL { get; set; }
        public string? RED_FLAG_PROVIAS { get; set; }
        public string? ESTATUS_DISEÑO2 { get; set; }
        public string? FC_INTEGRAL_CJ { get; set; }
        public string? UPDATE_02_01 { get; set; }
        public string? COMENTARIOS_Y_O_DEPENDENCIAS_CLARO { get; set; }
        public string? SEGUIMIENTO { get; set; }
        public string? CONTRATA_ING { get; set; }
        public string? AVANCES { get; set; }
        public string? SOLUCIÓN_ENERG_ { get; set; }
        public string? POTENCIA_REQ_KW { get; set; }
        public string? _CW { get; set; }
        public string? _ENERG { get; set; }
        public string? _PEXT { get; set; }
        public string? _TI { get; set; }
        public string? FECHAS_PEXT { get; set; }
        public string? ESTATUS_PEXT { get; set; }
        public string? PRORIDAD_PEXT { get; set; }
        public string? M_FO__EXISTENTE { get; set; }
        public string? M_FO__PROYECTADO { get; set; }
        public string? ESTATUS_CARTA_USO_POSTES { get; set; }
        public string? F_SOL_CARTA { get; set; }
        public string? N_DE_POSTES_PROYECTADOS { get; set; }
        public string? POSTE_EXISTENTES_ELECTRICA_BT { get; set; }
        public string? POSTES_EXISTENTE_AMOV { get; set; }
        public string? POSTE_EXISTENTES_ELECTRICA_MT { get; set; }
        public string? TOTAL_POSTES { get; set; }
        public string? TOTAL_POSTES_ELECTRICA { get; set; }
        public string? CONCESIONARIA { get; set; }
        public string? ESTATUS_EXP_ELECTRICO_PEXT { get; set; }
        public string? ESTATUS_ELECTRICA { get; set; }
        public string? N_DE_EXPEDIENTE { get; set; }
        public string? FECHA_DE_ING_EXPEDIENTE { get; set; }
        public string? DIAS_SIN_EXPEDIENTE2 { get; set; }
        public string? JEFE_CONCESIONARIA { get; set; }
        public string? GESTOR_ZONAL_RESPONSABLE { get; set; }
        public string? ESTATUS_INSPECCION { get; set; }
        public string? FC_INSPECCIÓN { get; set; }
        public string? FECHA_INSPECCION_REAL { get; set; }
        public string? RESPONSABLE_GESTION { get; set; }
        public string? COMENTARIOS { get; set; }
        public string? POSTES_OBSERVADOS { get; set; }
        public string? POSTES_FCC_VAL { get; set; }
        public string? F_VAL_FCC_ { get; set; }
        public string? MUNICIPALIDAD { get; set; }
        public string? EXPEDIENTE_MUNICIPAL { get; set; }
        public string? F_INGRESO_EXP_MUNI { get; set; }
        public string? FUIIT { get; set; }
        public string? COMENTARIO_EXP_MUNICIPAL { get; set; }
        public string? PMA { get; set; }
        public string? CIRA { get; set; }
        public string? PROVIAS { get; set; }
        public string? EVAP { get; set; }
        public string? SERVIDUMBRE { get; set; }
        public string? ESTATUS_PERMISOS_ESPECIALES { get; set; }
        public string? PERMISOS_ESPECIALES_VALIDADOS { get; set; }
        public string? F_FUIIT { get; set; }
        public string? F_PMA { get; set; }
        public string? F_CIRA { get; set; }
        public string? F_PROVIAS { get; set; }
        public string? F_EVAP { get; set; }
        public string? F_SERVIDUMBRE { get; set; }
        public string? FC_LICENCIA { get; set; }
        public string? FC_C_LICENCIA { get; set; }
        public string? LICENCIA { get; set; }
        public string? FIN_LICENCIA { get; set; }
        public string? DÍAS_PARA_VENCIM_ { get; set; }
        public string? INICIO_PEXT { get; set; }
        public string? FIN_PEXT { get; set; }
        public string? ESTATUS_PEXT2 { get; set; }
        public string? FECHAS_CW { get; set; }
        public string? ESTATUS_EJECUCION_CW { get; set; }
        public string? RED_FLAG_CW { get; set; }
        public string? TIPO_POSTE { get; set; }
        public string? ALT_POSTE { get; set; }
        public string? ESTATUS_POSTE { get; set; }
        public string? FECHA_POSTE { get; set; }
        public string? TRASLADO_POSTES { get; set; }
        public string? FECHA_TRASLADO { get; set; }
        public string? CW_PRELIMINAR { get; set; }
        public string? FECHA_CW { get; set; }
        public string? PARRES { get; set; }
        public string? FECHA_PARRES { get; set; }
        public string? PARARRAYOS { get; set; }
        public string? FECHA_PARARRAYOS { get; set; }
        public string? FC_PROYECTO { get; set; }
        public string? FC_C_PROYECTO { get; set; }
        public string? CWTS { get; set; }
        public string? FC_CW_INICIADO { get; set; }
        public string? FC_C_CW_INICIADO { get; set; }
        public string? INICIO_CW { get; set; }
        public string? FIN_CW { get; set; }
        public string? FECHAS_TI { get; set; }
        public string? ESTUDIO_LOS { get; set; }
        public string? ENVÍO_LOS { get; set; }
        public string? VALID_LOS { get; set; }
        public string? RFTI { get; set; }
        public string? INICIO_TI { get; set; }
        public string? ENLACE_VALIDADO { get; set; }
        public string? FIN_TI { get; set; }
        public string? FC_OA { get; set; }
        public string? FC_ACTA_COBERTURA { get; set; }
        public string? FECHAS_ENERG_ { get; set; }
        public string? ESTATUS_ENERGÍA { get; set; }
        public string? RED_FLAG_ENERGIA { get; set; }
        public string? CONCESIONARIAS { get; set; }
        public string? TARIFA_REQUERIDA { get; set; }
        public string? POTENCIA_REQUERIDA_WATTS_ { get; set; }
        public string? POTENCIA_CONTRATADA_KW { get; set; }
        public string? GESTOR { get; set; }
        public string? LOCALIDAD { get; set; }
        public string? ESTATUS_EXP_MUNICIPAL_AC { get; set; }
        public string? F_INGRESO_EXP_AC { get; set; }
        public string? T_TRANSCURRIDO_MUNI_AC { get; set; }
        public string? AUTORIZACION_MUNICIPAL_AC { get; set; }
        public string? COMENTARIOS2 { get; set; }
        public string? EXP_ELEC_AC { get; set; }
        public string? N_ATENCION { get; set; }
        public string? F__INGRESO_EXPEDIENTE { get; set; }
        public string? T_TRANSCURRIDO { get; set; }
        public string? FACTIBILIDAD { get; set; }
        public string? FECHA_FACT { get; set; }
        public string? DIAS_CON_FACTIBILIDAD { get; set; }
        public string? MURETE_ADEC { get; set; }
        public string? F_MURETE { get; set; }
        public string? METRAJE_AC__PROYECTADO { get; set; }
        public string? N_DE_POSTES_PROYECTADO { get; set; }
        public string? PRESUPUESTO { get; set; }
        public string? CONTRATO { get; set; }
        public string? MEDIDOR_O_SUMINISTRO { get; set; }
        public string? TABLERO { get; set; }
        public string? FC_ENERGIZADO { get; set; }
        public string? ACCIONES_A_TOMAR { get; set; }
        public string? FC_ENERGÍA_PROVISIONAL { get; set; }
        public string? INICIO_ENERGÍA { get; set; }
        public string? FIN_ENERGÍA { get; set; }
        public string? ENERGÍA_OK { get; set; }
        public string? COMENTARIOS_AC { get; set; }
        public string? W42 { get; set; }
        public string? W43 { get; set; }
        public string? W44 { get; set; }
        public string? W45 { get; set; }
        public string? W46 { get; set; }
        public string? W47 { get; set; }
        public string? W48 { get; set; }
        public string? W49 { get; set; }
        public string? W50 { get; set; }
        public string? W51 { get; set; }
        public string? W52 { get; set; }
        public string? W53 { get; set; }
        public string? W54 { get; set; }
        public string? W55 { get; set; }
        public string? W56 { get; set; }
        public string? W57 { get; set; }
        public string? W58 { get; set; }
        public string? W59 { get; set; }
        public string? W60 { get; set; }
        public string? W61 { get; set; }
        public string? W62 { get; set; }
        public string? W63 { get; set; }
        public string? W64 { get; set; }
        public string? W65 { get; set; }
        public string? W66 { get; set; }
        public string? W67 { get; set; }
        public string? W68 { get; set; }
        public string? W69 { get; set; }
        public string? W70 { get; set; }
        public string? W71 { get; set; }
        public string? W2_W1 { get; set; }
        public string? IMP_PEXT { get; set; }
        public string? ESTATUS_EJECUCION_PEXT { get; set; }
        public string? RED_FLAG_PEXT { get; set; }
        public string? ESTATUS_PERMISOS { get; set; }
        public string? VIABILIDAD { get; set; }
        public string? ESTADO_HW { get; set; }
        public string? F_SOL_FO { get; set; }
        public string? F_ASIG_FO { get; set; }
        public string? F_PAP_FO { get; set; }
        public string? F_RX_FO { get; set; }
        public string? _DIAS_ENTREGA_FO { get; set; }
        public string? CODIGO { get; set; }
        public string? DESCRIPTIONS { get; set; }
        public string? SPAM { get; set; }
        public string? METRAJE_SOLICITADO { get; set; }
        public string? SOT_CID { get; set; }
        public string? COD_POSTE { get; set; }
        public string? STATUS_DATA_PEXT { get; set; }
        public string? POSTES_FV_09 { get; set; }
        public string? POSTES_FV_11 { get; set; }
        public string? ESTATUS_POSTES_FV { get; set; }
        public string? POSTES_CAC_09 { get; set; }
        public string? POSTES_CAC_11 { get; set; }
        public string? ESTATUS_POSTES_CAC { get; set; }
        public string? TOTAL_POSTES_FINAL { get; set; }
        public string? ESTATUS_POSTES_GENERAL { get; set; }
        public string? ANALISTA_PEXT { get; set; }
        public string? CONTRATA_PEXT { get; set; }
        public string? F_INIC_EJEC { get; set; }
        public string? F_FIN_PEXT { get; set; }
        public string? W_PEXT_EJEC { get; set; }
        public string? POSTES { get; set; }
        public string? TENDIDO { get; set; }
        public string? FUSIONES { get; set; }
        public string? PINT { get; set; }
        public string? ACABADOS { get; set; }
        public string? _DE_HILOS_INSTALADOS { get; set; }
        public string? METRAJE_INSTALADO { get; set; }
        public string? PRIORIDAD { get; set; }
        public string? SEGUIMIENTO_PEXT { get; set; }
        public string? FÓRMULAS { get; set; }
        public string? VISITA_DE_CANDIDATOS { get; set; }
        public string? ENVÍO_DE_SAR { get; set; }
        public string? FIRMA_DE_CONTRATO { get; set; }
        public string? INGRESO_DE_CONTRATO { get; set; }
        public string? OTENCIÓN_CIRA { get; set; }
        public string? OTENCIÓN_PMA { get; set; }
        public string? OTENCIÓN_DIA { get; set; }
        public string? OTENCIÓN_DGAC { get; set; }
        public string? INGRESO_LICENCIA { get; set; }
        public string? REALIZAR_LOS { get; set; }
        public string? EJECUCIÓN_EMS { get; set; }
        public string? EJECUCIÓN_EMS_FE { get; set; }
        public string? RELEVAMIENTO_DE_TORRE { get; set; }
        public string? ENVÍO_PROYECTO { get; set; }
        public string? INICIO_DE_CW { get; set; }
        public string? LISTO_PARA_EQUIPOS { get; set; }
        public string? FIN_DE_CW { get; set; }
        public string? IMP_TI { get; set; }
        public string? ESTATUS_EJECUCION_TI { get; set; }
        public string? RED_FLAG_TI { get; set; }
        public string? TECNOLOGÍA { get; set; }
        public string? MODELO_ANTENA { get; set; }
        public string? CANTIDAD_SECTORES2 { get; set; }
        public string? TIPO { get; set; }
        public string? ESTADO_HW_TI { get; set; }
        public string? F_SOL_RF { get; set; }
        public string? F_ASIG_RF { get; set; }
        public string? F_PAP_RF { get; set; }
        public string? F_RX_RF { get; set; }
        public string? _DIAS_ENTREGA_RF { get; set; }
        public string? DF_4G { get; set; }
        public string? WOTX { get; set; }
        public string? SCRIPT { get; set; }
        public string? FO_PINT { get; set; }
        public string? SOPORTES_RF { get; set; }
        public string? CONTRATA_TI { get; set; }
        public string? F_ACT_REAL { get; set; }
        public string? W_ACT_REAL { get; set; }
        public string? PUESTA_EN_SERVICIO { get; set; }
        public string? ENVÍO_ACTA_COBERTURA { get; set; }
        public string? FECHA_ACTA_COBERTURA { get; set; }
        public string? CAPITALIZACIÓN { get; set; }
        public string? PRIORIDAD_TI { get; set; }
        public string? SEGUIMIENTO_TI { get; set; }
        public string? FÓRMULAS_ENERGÍA { get; set; }
        public string? SOLICITAR_FACTIBILIDAD { get; set; }
        public string? OBTENER_FACTIBILIDAD { get; set; }
        public string? SOLICITAR_PUNTO_DISEÑO { get; set; }
        public string? OBTENER_PUNTO_DISEÑO { get; set; }
        public string? INGRESO_PROY_CONCESIONARIA { get; set; }
        public string? INICIO_OBRAS_ENERGÍA { get; set; }
        public string? FIN_OBRAS_ENERGÍA { get; set; }
        public string? INSTALACIÓN_SUMINISTRO { get; set; }
        public string? FORECAST_CLARO { get; set; }
        public string? FC_GENERAL { get; set; }
        public string? WEEK_ACTIVACION { get; set; }
        public string? PROY_ { get; set; }
        public string? PRIORIDAD_CLARO { get; set; }
        public string? OT_PAP2 { get; set; }
        public int? IdZona { get; set; }
        public string? IdSite { get; set; }
        public decimal? CorreSite { get; set; }
        public int? Status_Claro { get; set; }
        public int? IdDepartamento { get; set; }
        public int? IdTransmision { get; set; }
        public int? IdProyecto { get; set; }
        public int? IdTorrera { get; set; }
        public int? IdTipoTorre { get; set; }
        public int? IdOnAir { get; set; }
        public int? IdActaCob { get; set; }
        public int? IdCapitalizacion { get; set; }
        public int? IdCandado { get; set; }
        public int? IdContacto { get; set; }
        public int? IdStatusIng { get; set; }
        public int? GIS_INGENIERIA2 { get; set; }
        public int? DATA_ING_TX_CLARO2 { get; set; }
        public int? HILOS_ASIG2 { get; set; }
        public int? AnalistaIng { get; set; }
        public int? idContrataResp { get; set; }
        public int? KMZ2 { get; set; }
        public int? REP_FOT_DISEno { get; set; }
        public int? IdPlanosPdf { get; set; }
        public int? IdDiagramaEmpalme { get; set; }
        public int? PptoDise { get; set; }
        public int? Status_Diseno { get; set; }
        public int? ESTATUS_OC2 { get; set; }
        public int? IdIngDinamica { get; set; }
        public int? PreInt { get; set; }
        public int? RED_FLAG_PROVIAS2 { get; set; }
        public int? StatusPext { get; set; }
        public int? PriPext { get; set; }
        public int? StatusCartaPoste { get; set; }
        public int? CONCESIONARIA2 { get; set; }
        public int? StatusExpPext { get; set; }
        public int? IdStatusElectrica { get; set; }
        public int? IdJefeConcesionaria { get; set; }
        public int? IdGestorZonal { get; set; }
        public int? ESTATUS_INSPECCION2 { get; set; }
        public int? IdRespGestion { get; set; }
        public int? IdExpMun { get; set; }
        public int? MUNICIPALIDAD2 { get; set; }
        public int? FUIIT2 { get; set; }
        public int? PMA2 { get; set; }
        public int? CIRA2 { get; set; }
        public int? PROVIAS2 { get; set; }
        public int? EVAP2 { get; set; }
        public int? SERVIDUMBRE2 { get; set; }
        public int? StatPermEspe { get; set; }
        public int? PermEspecial { get; set; }
        public int? StatusEjecCw { get; set; }
        public int? TipoPoste { get; set; }
        public int? AlturaPoste { get; set; }
        public int? StatusPoste { get; set; }
        public int? TrasladoPoste { get; set; }
        public int? CwPreliminar { get; set; }
        public int? Parres2 { get; set; }
        public int? Pararrayos2 { get; set; }
        public int? StatusEjecTi { get; set; }
        public int? Tecnologia { get; set; }
        public int? ModAntena { get; set; }
        public int? Tipo2 { get; set; }
        public int? EstHwTi { get; set; }
        public int? Df { get; set; }
        public int? WOTX2 { get; set; }
        public int? SCRIPT2 { get; set; }
        public int? FO_PINT2 { get; set; }
        public int? SOPORTES_RF2 { get; set; }
        public int? CONTRATA_TI2 { get; set; }
        public int? PtaServ { get; set; }
        public int? EnvActCob { get; set; }
        public int? Capitalizacion2 { get; set; }
        public int? PRIORIDAD_TI2 { get; set; }
        public int? StatusEnergia { get; set; }
        public int? CONCESIONARIAS2 { get; set; }
        public int? IdGestorEne { get; set; }
        public int? IdLocalidad { get; set; }
        public int? EstExpMunPal { get; set; }
        public int? idFact { get; set; }
        public int? MureteAdec { get; set; }
        public int? IdPresupuestado { get; set; }
        public int? IdContrato { get; set; }
        public int? IdSuministro { get; set; }
        public int? IdTablero { get; set; }
    }
}
