-- Database Schema
-- Generated on 2025-08-23T19:57:29.535Z

-- Total tables: 84

-- Table: Acceso_Perfil
-- Columns: 7
CREATE TABLE Acceso_Perfil (
    IdEmpleado int NOT NULL,
    Id int NOT NULL,
    IdUsuario nvarchar NOT NULL,
    IdPerfil int NOT NULL,
    IdArea int NOT NULL,
    IdEstado int,
    IdEmpleadoCj int
);

-- Table: Asistencia
-- Columns: 12
CREATE TABLE Asistencia (
    IdEmpleado int NOT NULL,
    FechaAsistencia datetime NOT NULL,
    IdEstado int NOT NULL,
    Comentario nvarchar,
    UsuarioCre int,
    FechaCreacion datetime,
    UsuarioAct int,
    FechaActualizacion datetime,
    Aprobado int,
    FechaAprobado datetime,
    IdAprobador int,
    Hora datetime
);

-- Table: CabBeneficio
-- Columns: 14
CREATE TABLE CabBeneficio (
    IdBeneficio numeric,
    IdTipoBeneficio int,
    IdEmpleado int,
    Monto numeric,
    Meses int,
    MesInicio datetime,
    IdAprobador int,
    FechaAprobador datetime,
    IdRechazo int,
    FechaRechazo datetime,
    IdCreacion int,
    FechaCreacion datetime,
    IdEstado int,
    IdAprobado bit
);

-- Table: cabGalvanizado
-- Columns: 35
CREATE TABLE cabGalvanizado (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroGalvanizado nvarchar NOT NULL,
    IdSolicitud nvarchar,
    ObsSolicitud nvarchar,
    Region nvarchar,
    Oc nvarchar,
    IdZona int,
    NroGuia nvarchar,
    Observacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Usuario nvarchar,
    IdSolicitante int,
    IdEstado int,
    OT nvarchar,
    NombreCliente nvarchar,
    NombreProyecto nvarchar,
    NombreTrabajo nvarchar,
    IdValidador int,
    IdValidador2 int,
    FormaEnvio int,
    RazonSocial int,
    Ubigeo nvarchar,
    Direccion nvarchar,
    Referencia nvarchar,
    IdConEntrega1 int,
    IdConEntrega2 int,
    IdMovimiento int,
    IdDespachador int,
    DirDocumento nvarchar
);

-- Table: CabLogistica
-- Columns: 25
CREATE TABLE CabLogistica (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    IdSolicitud nvarchar,
    ObsSolicitud nvarchar,
    Region nvarchar,
    Oc nvarchar,
    IdZona int,
    NroGuia nvarchar,
    Observacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Usuario nvarchar,
    IdSolicitante int,
    IdEstado int,
    OT nvarchar,
    NombreCliente nvarchar,
    NombreProyecto nvarchar,
    NombreTrabajo nvarchar,
    IdValidador int,
    FechaIngreso datetime
);

-- Table: CabMulta
-- Columns: 19
CREATE TABLE CabMulta (
    IdMulta numeric,
    CodUbigeo nvarchar,
    IdLugar int,
    FecEmision datetime,
    FecRecepcion datetime,
    IdTipDoc int,
    Referencia nvarchar,
    IdCriticidad int,
    IdDirigido int,
    IdCliente int,
    IdMedio int,
    Asunto nvarchar,
    IdRecibido int,
    Observacion nvarchar,
    FechaCreacion datetime,
    UsuarioCreacion nvarchar,
    Imagen nvarchar,
    IdEstado int,
    IdRespLegal int
);

-- Table: CabOrdenCompra
-- Columns: 27
CREATE TABLE CabOrdenCompra (
    IdOc int NOT NULL,
    IdSolicitante int,
    IdResponsable int,
    Subtotal numeric,
    Igv numeric,
    Total numeric,
    UsuarioCreacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    IdMoneda int,
    IdAprobador1 int,
    FechaAprobador1 datetime,
    IdAprobador2 int,
    FechaAprobador2 datetime,
    IdAprobador3 int,
    FechaAprobador3 datetime,
    IdComprobante int,
    IdRechazador int,
    FechaRechazado datetime,
    IdEstado int,
    Observacion nvarchar,
    IdValidador int,
    IdGestor int,
    FechaGestor datetime,
    IdFormaPago int,
    DiasPAgo int,
    Peso decimal
);

-- Table: CabPlanta
-- Columns: 35
CREATE TABLE CabPlanta (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    IdSolicitud nvarchar,
    ObsSolicitud nvarchar,
    Region nvarchar,
    Oc nvarchar,
    IdZona int,
    NroGuia nvarchar,
    Observacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Usuario nvarchar,
    IdSolicitante int,
    IdEstado int,
    OT nvarchar,
    NombreCliente nvarchar,
    NombreProyecto nvarchar,
    NombreTrabajo nvarchar,
    IdValidador int,
    IdValidador2 int,
    FormaEnvio int,
    RazonSocial int,
    Ubigeo nvarchar,
    Direccion nvarchar,
    Referencia nvarchar,
    IdConEntrega1 int,
    IdConEntrega2 int,
    IdMovimiento int,
    IdDespachador int,
    DirDocumento nvarchar
);

-- Table: CabSolicitud
-- Columns: 34
CREATE TABLE CabSolicitud (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    IdSolicitud nvarchar,
    ObsSolicitud nvarchar,
    Region nvarchar,
    Oc nvarchar,
    IdZona int,
    NroGuia nvarchar,
    Observacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Usuario nvarchar,
    IdSolicitante int,
    IdEstado int,
    OT nvarchar,
    NombreCliente nvarchar,
    NombreProyecto nvarchar,
    NombreTrabajo nvarchar,
    IdValidador int,
    IdValidador2 int,
    FormaEnvio int,
    RazonSocial int,
    Ubigeo nvarchar,
    Direccion nvarchar,
    Referencia nvarchar,
    IdConEntrega1 int,
    IdConEntrega2 int,
    IdMovimiento int,
    IdDespachador int
);

-- Table: CargaLogistica
-- Columns: 29
CREATE TABLE CargaLogistica (
    Correlativo uniqueidentifier NOT NULL DEFAULT (newid()),
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite numeric,
    IdTipoTrabajo int,
    CodPro nvarchar,
    PedidoSap nvarchar,
    IdSolicitud nvarchar,
    DescSite nvarchar,
    Solicitante nvarchar,
    IdSolicitante int,
    CantSolicitada numeric,
    CantSap numeric,
    Centro nvarchar,
    Almacen nvarchar,
    Lote nvarchar,
    Obs nvarchar,
    Region nvarchar,
    Oc nvarchar,
    Posicion nvarchar,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    UsuarioTmp nvarchar,
    Descripcion nvarchar,
    NombreCliente nvarchar,
    NombreProyecto nvarchar,
    NombreTrabajo nvarchar
);

-- Table: Cliente
-- Columns: 3
CREATE TABLE Cliente (
    IdCliente int NOT NULL,
    NombreCliente nvarchar NOT NULL,
    Estado int
);

-- Table: Constante
-- Columns: 8
CREATE TABLE Constante (
    Sociedad nvarchar NOT NULL,
    Programa nvarchar NOT NULL,
    Campo nvarchar NOT NULL,
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL,
    ValorFin nvarchar NOT NULL,
    Detalle nvarchar,
    Adicional nvarchar
);

-- Table: CopiaLogOperaciones
-- Columns: 10
CREATE TABLE CopiaLogOperaciones (
    OT nvarchar,
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite numeric,
    Campo nvarchar,
    Valor nvarchar,
    IdUsuario nvarchar,
    FechaCreacion datetime,
    ValorNuevo nvarchar
);

-- Table: CuentaEmpleado
-- Columns: 9
CREATE TABLE CuentaEmpleado (
    IdEmpleado int,
    idCargo int,
    IdBanco int,
    Cuenta nvarchar,
    CuentaInter nvarchar,
    NombreCta nvarchar,
    UsuarioCreacion nvarchar,
    FechaCreacion nvarchar,
    Estado int
);

-- Table: Db_Operaciones_Cj
-- Columns: 268
CREATE TABLE Db_Operaciones_Cj (
    OT nvarchar NOT NULL,
    FechaInicio datetime,
    IdZona int,
    IdSite nvarchar,
    CorreSite numeric,
    Status_Claro int,
    IdDepartamento int,
    IdFarEnd nvarchar,
    IdTransmision int,
    IdProyecto int,
    IdTorrera int,
    IdTipoTorre int,
    Altura numeric,
    CantSect int,
    LPE datetime,
    IdOnAir int,
    IdActaCob int,
    IdCapitalizacion int,
    NroOc nvarchar,
    MontoCw numeric,
    MontoEnergia numeric,
    MontoPext numeric,
    MontoTi numeric,
    Monto numeric,
    Latitud nvarchar,
    Longitud nvarchar,
    Direccion nvarchar,
    IdCandado int,
    IdContacto int,
    Telefono nvarchar,
    IdStatusIng int,
    GIS_INGENIERIA int,
    DATA_ING_TX_CLARO int,
    F_DATA_ING_SOL_TX datetime,
    DIAS_DATA int,
    F_DATA_ING_RX datetime,
    HILOS_ASIG int,
    F_SOL_ASIG_HILOS datetime,
    F_RX_ASIG_HILOS datetime,
    ID_FAREND nvarchar,
    AnalistaIng int,
    NroHilos int,
    idContrataResp int,
    FecAsigCon datetime,
    F_LEV_CAMPO datetime,
    KMZ int,
    REP_FOT_DISEno int,
    IdPlanosPdf int,
    IdDiagramaEmpalme int,
    PptoDise int,
    fecDisenoPext datetime,
    TIEMPO_SIN_VAL int,
    FecDisenoPextValidado datetime,
    Status_Diseno int,
    OBSERVACIONES nvarchar,
    metradoDiseno numeric,
    MetradoExistente numeric,
    ESTATUS_OC int,
    IdIngDinamica int,
    PreInt int,
    RED_FLAG_PROVIAS int,
    SolucionEmerg nvarchar,
    PotenciaKw numeric,
    PorcenCw numeric,
    PorcenEnergia numeric,
    PorcenPext numeric,
    PorcenTi numeric,
    FechaPext datetime,
    StatusPext int,
    PriPext int,
    M_FO_EXISTENTE numeric,
    M_FO_PROYECTADO numeric,
    StatusCartaPoste int,
    F_SOL_CARTA datetime,
    NroPostesProy nvarchar,
    NroPostesExBt int,
    NroPostesExAmov int,
    NroPostesExMt int,
    TotalPostesElec int,
    TotalPostes int,
    CONCESIONARIA int,
    StatusExpPext int,
    IdStatusElectrica int,
    NroExpediente nvarchar,
    FecIngExpediente datetime,
    IdJefeConcesionaria int,
    IdGestorZonal int,
    ESTATUS_INSPECCION int,
    FecInsp datetime,
    IdRespGestion int,
    PostesObs int,
    POSTES_FCC_VAL int,
    F_VAL_FCC int,
    IdExpMun int,
    MUNICIPALIDAD int,
    fecIngMuni datetime,
    FUIIT int,
    ComenExpMun nvarchar,
    PMA int,
    CIRA int,
    PROVIAS int,
    EVAP int,
    SERVIDUMBRE int,
    StatPermEspe int,
    PermEspecial int,
    F_FUIIT datetime,
    F_PMA datetime,
    F_CIRA datetime,
    F_PROVIAS datetime,
    F_EVAP datetime,
    F_SERVIDUMBRE datetime,
    FC_Licencia datetime,
    Licencia int,
    Fin_Licencia datetime,
    DiasVenc int,
    StatusEjecCw int,
    RedFlagCw nvarchar,
    TipoPoste int,
    AlturaPoste int,
    StatusPoste int,
    FecPoste datetime,
    TrasladoPoste int,
    FecTraslado datetime,
    CwPreliminar int,
    FechaCw datetime,
    Parres int,
    FecParres datetime,
    Pararrayos int,
    FecPararayos datetime,
    FcProyecto int,
    CWTS nvarchar,
    Inicio_CW datetime,
    Fi_CW datetime,
    StatusEjecTi int,
    RED_FLAG_TI nvarchar,
    Tecnologia int,
    ModAntena int,
    CantSectores int,
    Tipo int,
    EstHwTi int,
    F_SOL_RF datetime,
    F_ASIG_RF datetime,
    F_PAP_RF datetime,
    F_RX_RF datetime,
    NroDiasRf int,
    Df int,
    WOTX int,
    SCRIPT int,
    FO_PINT int,
    SOPORTES_RF int,
    CONTRATA_TI int,
    F_ACT_REAL datetime,
    W_ACT_REAL int,
    PtaServ int,
    EnvActCob int,
    FecActCob datetime,
    Capitalizacion int,
    PRIORIDAD_TI int,
    SEGUIMIENTO_TI nvarchar,
    StatusEnergia int,
    RedCw nvarchar,
    CONCESIONARIAS int,
    TARIFA_REQUERIDA numeric,
    PotenciaReq numeric,
    PotContratada numeric,
    IdGestorEne int,
    IdLocalidad int,
    EstExpMunPal int,
    FecIngExpAc datetime,
    tTransMuniAc int,
    COMENTARIOS nvarchar,
    ExpElec nvarchar,
    NroAtencion nvarchar,
    FecIngExp datetime,
    tTrans int,
    idFact int,
    fecFact datetime,
    diasFact int,
    MureteAdec int,
    F_MURETE datetime,
    MetrajeProy numeric,
    NroPostesproy1 int,
    IdPresupuestado int,
    IdContrato int,
    IdSuministro int,
    IdTablero int,
    Fc_energizado datetime,
    FcEneProv datetime,
    FecIniEnergia datetime,
    FinFecEneriga datetime,
    ComentariosAC nvarchar,
    W01 nvarchar,
    W02 nvarchar,
    W03 nvarchar,
    W04 nvarchar,
    W05 nvarchar,
    W06 nvarchar,
    W07 nvarchar,
    W08 nvarchar,
    W09 nvarchar,
    W10 nvarchar,
    W11 nvarchar,
    W12 nvarchar,
    W13 nvarchar,
    W14 nvarchar,
    W15 nvarchar,
    W16 nvarchar,
    W17 nvarchar,
    W18 nvarchar,
    W19 nvarchar,
    W20 nvarchar,
    W21 nvarchar,
    W22 nvarchar,
    W23 nvarchar,
    W24 nvarchar,
    W25 nvarchar,
    W26 nvarchar,
    W27 nvarchar,
    W28 nvarchar,
    W29 nvarchar,
    W30 nvarchar,
    StatusEjecPext int,
    redFlagPext nvarchar,
    IdStatusPext int,
    Viabilidad int,
    ESTADO_HW int,
    F_SOL_FO datetime,
    F_ASIG_FO datetime,
    F_PAP_FO datetime,
    F_RX_FO datetime,
    NroEntFo int,
    COD_POSTE int,
    STATUS_DATA_PEXT int,
    PosFib09 int,
    PosFib11 int,
    ESTATUS_POSTES_FV int,
    PosCac09 int,
    PosCac11 int,
    StatusPostesCac int,
    TotalPostesFinal int,
    StatusPostesgral int,
    AnalistaPext int,
    CONTRATA_PEXT int,
    F_INIC_EJEC datetime,
    F_FIN_PEXT datetime,
    W_PEXT_EJEC int,
    POSTES int,
    TENDIDO int,
    FUSIONES int,
    PINT int,
    ACABADOS int,
    NroHilosInstalados int,
    MetrajeInstal numeric,
    Prioridad int,
    SegPext nvarchar,
    StatusEjecucionTi int,
    RedFlgTi nvarchar,
    FecAct datetime,
    W_ACT int,
    IdProyecto1 int,
    PrioridadClaro int,
    Ot_Pap2 int,
    usuarioCreacion nvarchar,
    fechaCreacion datetime,
    IdEstado int,
    OPE_STAT_INGE_PEXT int,
    Status_Cj int,
    IdCliente int
);

-- Table: DET_IMPORTAR
-- Columns: 89
CREATE TABLE DET_IMPORTAR (
    OcPos nvarchar,
    OT nvarchar,
    PAP nvarchar,
    IdSite nvarchar,
    Correlativo int,
    IdTipoTrabajo nvarchar,
    IdWork nvarchar,
    IdProyecto int,
    IdZona int,
    IdEmpleado nvarchar,
    FecAsignacion nvarchar,
    MES nvarchar,
    ANO nvarchar,
    Estado_OC nvarchar,
    Nro_Oc nvarchar,
    Posicion nvarchar,
    FechaOc nvarchar,
    MontoOc numeric,
    MontoLiq numeric,
    LiqPap numeric,
    ESTADO_EA nvarchar,
    FechaEa nvarchar,
    TIEMPO_EA nvarchar,
    ANTIG_EA nvarchar,
    CENFILE nvarchar,
    STATUS_GIS nvarchar,
    Status_Atp nvarchar,
    Status_Folio int,
    Comentarios nvarchar,
    EA int,
    GIS_SMW nvarchar,
    STATUS_PAP nvarchar,
    Status_Fact nvarchar,
    Mes2 nvarchar,
    Status_Cj nvarchar,
    MesActivacion nvarchar,
    FecActivaPap nvarchar,
    FecActivaF nvarchar,
    Status_Gerencia nvarchar,
    Gerencia2 nvarchar,
    ESTING nvarchar,
    PLANO nvarchar,
    VALMET nvarchar,
    STATUS_CW nvarchar,
    STATUS_RINI nvarchar,
    StatusClaroMod nvarchar,
    FecActMod nvarchar,
    LiqMod nvarchar,
    FolioMod nvarchar,
    Status_Claro nvarchar,
    F_act_Real nvarchar,
    FOLIO_DENSI nvarchar,
    LIQ_DENSI nvarchar,
    Status_Ro nvarchar,
    Liquidacion nvarchar,
    Ivan nvarchar,
    Site nvarchar,
    TipoTrabajo nvarchar,
    Work nvarchar,
    Proyecto nvarchar,
    Zona nvarchar,
    Empleado nvarchar,
    Folio nvarchar,
    EaTxt nvarchar,
    FechaActivacion nvarchar,
    Folio_Ro nvarchar,
    Corte nvarchar,
    Facturado nvarchar,
    IdCliente int,
    Cliente nvarchar,
    Pext_Ro nvarchar,
    Folio_Roll_Pext nvarchar,
    Pext_densi nvarchar,
    Folio_densi_pext nvarchar,
    NroInterno numeric,
    IdEstado int,
    AnoGestion numeric,
    IdStatusClaro int,
    IdActualizar int,
    StatusOt nvarchar,
    StatusOt2 nvarchar,
    IdStatusOt int,
    IdStatusOt2 int,
    Folio2 nvarchar,
    IdFolio2 int,
    Capitalizacion nvarchar,
    IdStatusCj int,
    ATP nvarchar,
    PrePasivo nvarchar
);

-- Table: DetalleMulta
-- Columns: 19
CREATE TABLE DetalleMulta (
    IdMulta numeric,
    IdMoneda int,
    IdSolicitado int,
    IdAtendido int,
    FecRec datetime,
    FecObj datetime,
    IdGerencia int,
    IdDireccion int,
    IdContrata int,
    IdResponsable int,
    IdEstado int,
    TxtInfraccion nvarchar,
    TxtMedida nvarchar,
    TxtAfectacion nvarchar,
    TxtConcepto nvarchar,
    TxtLugar nvarchar,
    Usuario nvarchar,
    FechaCreacion date,
    HoraCreacion datetime
);

-- Table: DetBeneficio
-- Columns: 8
CREATE TABLE DetBeneficio (
    IdBeneficio numeric,
    MesPago nvarchar,
    Monto numeric,
    IdEstado int,
    IdUsuarioPago int,
    FechaPago datetime,
    IdActualizacion int,
    FechaActualizacion datetime
);

-- Table: detGalvanizado
-- Columns: 102
CREATE TABLE detGalvanizado (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroGalvanizado nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    Correlativo nvarchar NOT NULL,
    Serie nvarchar,
    CodPap nvarchar,
    CantSap numeric,
    Centro nvarchar,
    Almacen nvarchar,
    Lote nvarchar,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    IdEstado int,
    Observacion nvarchar,
    Comentario nvarchar,
    LinReg int,
    NroEnvio int,
    IdClienteOrigen int,
    IdProyectoOrigen int,
    IdSiteOrigen nvarchar,
    CorreSiteOrigen numeric,
    TipoTrabajoOrigen nvarchar,
    RutaImagen nvarchar,
    IdDespacho bit,
    ComenEnvio nvarchar,
    FechaEnvio datetime,
    HoraEnvio datetime,
    NroGuia nvarchar,
    IdAgencia int,
    MontoEnvio numeric,
    IdRespEnvio int,
    FechaEntrega datetime,
    FechaEnviado datetime,
    Aplica int,
    FechaRecojo datetime,
    ImagenEnvio nvarchar,
    IdUbicacion int,
    IdRespCampo int,
    FechaCampo datetime,
    UsuarioMod nvarchar,
    FechaAprobar datetime,
    IdRespAprobar int,
    FechaDespacho datetime,
    IdRespDespacho int,
    FechaSolicitud datetime,
    IdRespSolicitud int,
    ImagenSolicitud nvarchar,
    IdRespRecojo int,
    FechaCierre datetime,
    IdRespCierre int,
    UsuarioCreacion nvarchar,
    FechaCreacion datetime,
    ImagenCierre nvarchar,
    IdRespObs int,
    IdRespRec int,
    FechaRechazar datetime,
    FechaObs datetime,
    RutaDesImagen nvarchar,
    NroCierre int,
    NumeroCierre nvarchar,
    CantDesp numeric,
    FechaCruce datetime,
    IdRespCruce int,
    CantEnvio numeric,
    CantCampo numeric,
    CantCruce numeric,
    CantCierre numeric,
    CantFolio numeric,
    NroFolio nvarchar,
    NroOc nvarchar,
    NroPosicion nvarchar,
    FechaTermino datetime,
    IdRespTermino int,
    IdBloqueo int,
    NroGuiaRetorno nvarchar,
    IdAgenciaRetorno int,
    Region nvarchar,
    PosicionLog nvarchar,
    RutaPre nvarchar,
    IdRespReq int,
    FechaReq datetime,
    IdRespCompra int,
    FechaCompra datetime,
    IdRespFab int,
    FechaFab datetime,
    IdRespGal int,
    FechaGal datetime,
    IdocRel int,
    CorrelativoRel numeric,
    IdSub int,
    RutaSolicitud nvarchar,
    IdEstadoStock int,
    FechaFinFab datetime,
    IdEstadoFab int,
    PesoDet decimal,
    NroSolicitud nvarchar
);

-- Table: DetLogistica
-- Columns: 52
CREATE TABLE DetLogistica (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    Correlativo uniqueidentifier NOT NULL DEFAULT (newid()),
    Serie nvarchar,
    CodPap nvarchar,
    CantSap numeric,
    Centro nvarchar,
    Almacen nvarchar,
    Lote nvarchar,
    Usuario nvarchar,
    Fecha date,
    Hora datetime,
    IdEstado int,
    Observacion nvarchar,
    Comentario nvarchar,
    LinReg int,
    NroEnvio int,
    IdClienteOrigen int,
    IdProyectoOrigen int,
    IdSiteOrigen nvarchar,
    CorreSiteOrigen numeric,
    TipoTrabajoOrigen nvarchar,
    RutaImagen nvarchar,
    IdDespacho bit,
    CantRecepcion numeric,
    FecIngreso date,
    Guia nvarchar,
    Guia2 nvarchar,
    IdUbicacion int,
    IdZonaAlmacen int,
    FecIngreso2 date,
    CantSolNew numeric,
    FechaRecepcion datetime,
    FechaSerie datetime,
    FechaValidacion datetime,
    FechaSolicitud datetime,
    FechaAprobar datetime,
    FechaDespacho datetime,
    FechaEnvio datetime,
    UsuarioMod nvarchar,
    Alm2025 bit,
    IdActivar int,
    FechaActivar datetime,
    CantBloqueada numeric,
    CantDisponible numeric,
    Region nvarchar,
    OC nvarchar
);

-- Table: DetOrdenCompra
-- Columns: 29
CREATE TABLE DetOrdenCompra (
    IdOc int,
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    Correlativo numeric,
    IdTipoTrabajo int,
    IdTarea int,
    TipoTrabajo nvarchar,
    Detalle nvarchar,
    Cantidad int,
    PrecioUnitario numeric,
    UsuarioCreacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Ot nvarchar,
    IdAprobador1 int,
    FechaAprobador1 datetime,
    IdAprobador2 int,
    FechaAprobador2 datetime,
    IdAprobador3 int,
    FechaAprobador3 datetime,
    IdComprobante int,
    Fila int,
    MontoAdela numeric,
    IdEstado int,
    IdGestor int,
    FechaGestor datetime,
    ImgOc nvarchar,
    ImgPresupuesto nvarchar
);

-- Table: detPlanilla
-- Columns: 82
CREATE TABLE detPlanilla (
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    IdTipoTrabajo int NOT NULL,
    IdTarea int NOT NULL,
    Correlativo numeric NOT NULL,
    FecIngreso nvarchar,
    Detalle text,
    IdResponsable int,
    IdCliente int NOT NULL,
    IdBien int,
    IdComprobante int,
    RUC nvarchar,
    Serie nvarchar,
    IdTipoPago int,
    FecEmision nvarchar,
    TipoMoneda int,
    Total numeric,
    Subtotal numeric,
    IGV numeric,
    IdRendicion int,
    Observacion nvarchar,
    Comentario nvarchar,
    IdSolicitante int,
    IdGestor int,
    IdValidador int,
    IdEjecutor int,
    IdTransferencia int,
    IdBanco int,
    IdMoneda2 int,
    IdRendir int,
    FechaDeposito nvarchar,
    IdRetencion int,
    Otro nvarchar,
    Otro2 nvarchar,
    Otro3 nvarchar,
    Otro4 nvarchar,
    Estado int,
    CorreSite int,
    FechaPropuesta nvarchar,
    IdBancoCta int,
    Cuenta nvarchar,
    CuentaInter nvarchar,
    NombreCta nvarchar,
    NombreProyecto nvarchar,
    Site nvarchar,
    Tipo_Trabajo nvarchar,
    Tarea nvarchar,
    Responsable nvarchar,
    Cliente nvarchar,
    Bien nvarchar,
    Comprobante nvarchar,
    Pago nvarchar,
    Moneda nvarchar,
    Rendicion nvarchar,
    Solicitante nvarchar,
    Gestor nvarchar,
    Validador nvarchar,
    Ejecutor nvarchar,
    Transferencia nvarchar,
    Banco nvarchar,
    Moneda2 nvarchar,
    Rendir nvarchar,
    Retencion nvarchar,
    FechaAprobador nvarchar,
    Usuario nvarchar,
    FechaCreacion nvarchar,
    HoraCreacion nvarchar,
    Ot nvarchar,
    TipoPago nvarchar,
    TipoCambio numeric,
    NroFactura nvarchar,
    IdUrgente bit,
    IdReAprobador int,
    FechaReAprobador datetime,
    IdOc int,
    Fila int,
    IdTipoDoc int,
    ImgSustento nvarchar,
    ImgFactura nvarchar,
    IdUsuarioFactura int,
    FecImaFactura datetime,
    NroOperacion nvarchar
);

-- Table: DetPlanta
-- Columns: 108
CREATE TABLE DetPlanta (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    Correlativo nvarchar NOT NULL,
    Serie nvarchar,
    CodPap nvarchar,
    CantSap numeric,
    Centro nvarchar,
    Almacen nvarchar,
    Lote nvarchar,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    IdEstado int,
    Observacion nvarchar,
    Comentario nvarchar,
    LinReg int,
    NroEnvio int,
    IdClienteOrigen int,
    IdProyectoOrigen int,
    IdSiteOrigen nvarchar,
    CorreSiteOrigen numeric,
    TipoTrabajoOrigen nvarchar,
    RutaImagen nvarchar,
    IdDespacho bit,
    ComenEnvio nvarchar,
    FechaEnvio datetime,
    HoraEnvio datetime,
    NroGuia nvarchar,
    IdAgencia int,
    MontoEnvio numeric,
    IdRespEnvio int,
    FechaEntrega datetime,
    FechaEnviado datetime,
    Aplica int,
    FechaRecojo datetime,
    ImagenEnvio nvarchar,
    IdUbicacion int,
    IdRespCampo int,
    FechaCampo datetime,
    UsuarioMod nvarchar,
    FechaAprobar datetime,
    IdRespAprobar int,
    FechaDespacho datetime,
    IdRespDespacho int,
    FechaSolicitud datetime,
    IdRespSolicitud int,
    ImagenSolicitud nvarchar,
    IdRespRecojo int,
    FechaCierre datetime,
    IdRespCierre int,
    UsuarioCreacion nvarchar,
    FechaCreacion datetime,
    ImagenCierre nvarchar,
    IdRespObs int,
    IdRespRec int,
    FechaRechazar datetime,
    FechaObs datetime,
    RutaDesImagen nvarchar,
    NroCierre int,
    NumeroCierre nvarchar,
    CantDesp numeric,
    FechaCruce datetime,
    IdRespCruce int,
    CantEnvio numeric,
    CantCampo numeric,
    CantCruce numeric,
    CantCierre numeric,
    CantFolio numeric,
    NroFolio nvarchar,
    NroOc nvarchar,
    NroPosicion nvarchar,
    FechaTermino datetime,
    IdRespTermino int,
    IdBloqueo int,
    NroGuiaRetorno nvarchar,
    IdAgenciaRetorno int,
    Region nvarchar,
    PosicionLog nvarchar,
    RutaPre nvarchar,
    IdRespReq int,
    FechaReq datetime,
    IdRespCompra int,
    FechaCompra datetime,
    IdRespFab int,
    FechaFab datetime,
    IdRespGal int,
    FechaGal datetime,
    IdocRel int,
    CorrelativoRel numeric,
    IdSub int,
    RutaSolicitud nvarchar,
    IdEstadoStock int,
    FechaFinFab datetime,
    IdEstadoFab int,
    PesoDet decimal,
    FechaFinGal datetime,
    IdProveedorGal int,
    ImgPckGal nvarchar,
    ImgGuiaGal nvarchar,
    ImgDespacho nvarchar,
    IdEstadoDespacho int,
    IdEstAdicional int
);

-- Table: detplantaDoc
-- Columns: 17
CREATE TABLE detplantaDoc (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    Correlativo nvarchar NOT NULL,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    IdEstado int,
    Observacion nvarchar,
    FechaCarga datetime,
    IdRespCarga int,
    ImagenCarga nvarchar
);

-- Table: DetSolicitud
-- Columns: 84
CREATE TABLE DetSolicitud (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    Correlativo nvarchar NOT NULL DEFAULT (newid()),
    Serie nvarchar,
    CodPap nvarchar,
    CantSap numeric,
    Centro nvarchar,
    Almacen nvarchar,
    Lote nvarchar,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    IdEstado int,
    Observacion nvarchar,
    Comentario nvarchar,
    LinReg int,
    NroEnvio int,
    IdClienteOrigen int,
    IdProyectoOrigen int,
    IdSiteOrigen nvarchar,
    CorreSiteOrigen numeric,
    TipoTrabajoOrigen nvarchar,
    RutaImagen nvarchar,
    IdDespacho bit,
    ComenEnvio nvarchar,
    FechaEnvio datetime,
    HoraEnvio datetime,
    NroGuia nvarchar,
    IdAgencia int,
    MontoEnvio numeric,
    IdRespEnvio int,
    FechaEntrega datetime,
    FechaEnviado datetime,
    Aplica int,
    FechaRecojo datetime,
    ImagenEnvio nvarchar,
    IdUbicacion int,
    IdRespCampo int,
    FechaCampo datetime,
    UsuarioMod nvarchar,
    FechaAprobar datetime,
    IdRespAprobar int,
    FechaDespacho datetime,
    IdRespDespacho int,
    FechaSolicitud datetime,
    IdRespSolicitud int,
    ImagenSolicitud nvarchar,
    IdRespRecojo int,
    FechaCierre datetime,
    IdRespCierre int,
    UsuarioCreacion nvarchar,
    FechaCreacion datetime,
    ImagenCierre nvarchar,
    IdRespObs int,
    IdRespRec int,
    FechaRechazar datetime,
    FechaObs datetime,
    RutaDesImagen nvarchar,
    NroCierre int,
    NumeroCierre nvarchar,
    CantDesp numeric,
    FechaCruce datetime,
    IdRespCruce int,
    CantEnvio numeric,
    CantCampo numeric,
    CantCruce numeric,
    CantCierre numeric,
    CantFolio numeric,
    NroFolio nvarchar,
    NroOc nvarchar,
    NroPosicion nvarchar,
    FechaTermino datetime,
    IdRespTermino int,
    IdBloqueo int,
    NroGuiaRetorno nvarchar,
    IdAgenciaRetorno int,
    Region nvarchar,
    PosicionLog nvarchar
);

-- Table: DocumentosMulta
-- Columns: 10
CREATE TABLE DocumentosMulta (
    IdMulta numeric,
    ContaDoc int,
    TxtDoc nvarchar,
    TxtOficio nvarchar,
    TxtImagen nvarchar,
    IdTipo int,
    Usuario nvarchar,
    FechaCreacion date,
    HoraCreacion datetime,
    IdEstado int
);

-- Table: Empleado
-- Columns: 17
CREATE TABLE Empleado (
    IdEmpleado int NOT NULL,
    NombreEmpleado nvarchar NOT NULL,
    InicialesEmpleado nvarchar NOT NULL,
    IdCargo int NOT NULL,
    IdDocumento int,
    NroDocumento nvarchar,
    Telefono nvarchar,
    Correo nvarchar,
    UsuarioCre nvarchar,
    FechaCreacion datetime,
    IdEstado int,
    UsuarioDel nvarchar,
    FechaEliminar datetime,
    Direccion nvarchar,
    IdTipoEmpleado int,
    IdEmpleadoCj int,
    IdCheque int
);

-- Table: EmpleadoAnt
-- Columns: 8
CREATE TABLE EmpleadoAnt (
    IdEmpleado int NOT NULL,
    NombreEmpleado nvarchar NOT NULL,
    InicialesEmpleado nvarchar NOT NULL,
    IdCargo int NOT NULL,
    IdDocumento int,
    NroDocumento nvarchar,
    Telefono nvarchar,
    Correo nvarchar
);

-- Table: EmpleadoCj
-- Columns: 25
CREATE TABLE EmpleadoCj (
    IdEmpleado int NOT NULL,
    NombreEmpleado nvarchar NOT NULL,
    InicialesEmpleado nvarchar NOT NULL,
    IdCargo int NOT NULL,
    IdDocumento int,
    NroDocumento nvarchar,
    Telefono nvarchar,
    Correo nvarchar,
    UsuarioCre nvarchar,
    FechaCreacion datetime,
    IdEstado int,
    UsuarioDel nvarchar,
    FechaEliminar datetime,
    Direccion nvarchar,
    IdTipoEmpleado int,
    FechaIniLaboral datetime,
    FechaFinlaboral datetime,
    IdActivo bit,
    IdAptobeneficio int,
    IdSexo int,
    IdEmpRel int,
    NroAlterno nvarchar,
    IdEstable int,
    IdEmpleadoAnt int,
    FechaBaja datetime
);

-- Table: EmpleadoCjAdministracion
-- Columns: 8
CREATE TABLE EmpleadoCjAdministracion (
    IdEmpleado int NOT NULL,
    InicioContrato datetime NOT NULL,
    Activo int NOT NULL,
    CantMeses int,
    FechaCreacion datetime,
    HoraCreacion datetime,
    UsuarioCreacion nvarchar,
    IdEstado int
);

-- Table: EmpleadoCjAdmLog
-- Columns: 8
CREATE TABLE EmpleadoCjAdmLog (
    IdEmpleado int NOT NULL,
    InicioContrato datetime NOT NULL,
    Activo int NOT NULL,
    CantMeses int,
    FechaCreacion datetime,
    HoraCreacion datetime,
    UsuarioCreacion nvarchar,
    IdEstado int
);

-- Table: EmpleadoCjDetalle
-- Columns: 12
CREATE TABLE EmpleadoCjDetalle (
    IdEmpleadoCj int,
    IdEmpresaCj int,
    IdClienteCj int,
    IdAreaCj int,
    IdUbicacionCj int,
    IdResponsableCj int,
    IdPrimerVacaciones int,
    IdSegundoVacaciones int,
    IdTerceroVacaciones int,
    IdPrimeroOc int,
    IdSegundoOc int,
    IdTerceroOc int
);

-- Table: EmpleadoCjPerfil
-- Columns: 7
CREATE TABLE EmpleadoCjPerfil (
    IdEmpleadoCj int NOT NULL,
    IdPerfil int NOT NULL,
    IdEstado int,
    IdCreacion int,
    FechaCreacion datetime,
    IdModificar int,
    FechaModificacion datetime
);

-- Table: EmpleadoClaro
-- Columns: 3
CREATE TABLE EmpleadoClaro (
    IdEmpleadoClaro int NOT NULL,
    IdCargoEmpleado int,
    NombreEmpleado nvarchar
);

-- Table: EmpleadoEntrega
-- Columns: 8
CREATE TABLE EmpleadoEntrega (
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite numeric,
    PedidoSap nvarchar,
    NroSolicitud nvarchar,
    Correlativo uniqueidentifier DEFAULT (newid()),
    IdEmpleado int
);

-- Table: EmpleadoOtros
-- Columns: 17
CREATE TABLE EmpleadoOtros (
    IdEmpleadoCj int,
    IdEstado int,
    Fecha datetime,
    IdActivo int,
    IdAutorizado int,
    FechaAutorizado date,
    FechaInicio date,
    FechaFin date,
    FechaPre date,
    FechaPrimera date,
    IdPre int,
    IdPrimera int,
    IdGestor int,
    Usuario nvarchar,
    FechaCreacion datetime,
    IdRechazo int,
    FechaRechazo datetime
);

-- Table: GastosWeb
-- Columns: 8
CREATE TABLE GastosWeb (
    IdCorrelativo numeric NOT NULL,
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    IdEmpleado int,
    Fecha nvarchar,
    Monto numeric,
    Moneda int
);

-- Table: Importar
-- Columns: 94
CREATE TABLE Importar (
    OcPos nvarchar,
    OT nvarchar,
    PAP nvarchar,
    IdSite nvarchar,
    Correlativo int,
    IdTipoTrabajo nvarchar,
    IdWork nvarchar,
    IdProyecto int,
    IdZona int,
    IdEmpleado nvarchar,
    FecAsignacion nvarchar,
    MES nvarchar,
    ANO nvarchar,
    Estado_OC nvarchar,
    Nro_Oc nvarchar,
    Posicion nvarchar,
    FechaOc nvarchar,
    MontoOc numeric,
    MontoLiq numeric,
    LiqPap numeric,
    ESTADO_EA nvarchar,
    FechaEa nvarchar,
    TIEMPO_EA nvarchar,
    ANTIG_EA nvarchar,
    CENFILE nvarchar,
    STATUS_GIS nvarchar,
    Status_Atp nvarchar,
    Status_Folio int,
    Comentarios nvarchar,
    EA int,
    GIS_SMW nvarchar,
    STATUS_PAP nvarchar,
    Status_Fact nvarchar,
    Mes2 nvarchar,
    Status_Cj nvarchar,
    MesActivacion nvarchar,
    FecActivaPap nvarchar,
    FecActivaF nvarchar,
    Status_Gerencia nvarchar,
    Gerencia2 nvarchar,
    ESTING nvarchar,
    PLANO nvarchar,
    VALMET nvarchar,
    STATUS_CW nvarchar,
    STATUS_RINI nvarchar,
    StatusClaroMod nvarchar,
    FecActMod nvarchar,
    LiqMod nvarchar,
    FolioMod nvarchar,
    Status_Claro nvarchar,
    F_act_Real nvarchar,
    FOLIO_DENSI nvarchar,
    LIQ_DENSI nvarchar,
    Status_Ro nvarchar,
    Liquidacion nvarchar,
    Ivan nvarchar,
    Site nvarchar,
    TipoTrabajo nvarchar,
    Work nvarchar,
    Proyecto nvarchar,
    Zona nvarchar,
    Empleado nvarchar,
    Folio nvarchar,
    EaTxt nvarchar,
    FechaActivacion nvarchar,
    Folio_Ro nvarchar,
    Corte nvarchar,
    Facturado nvarchar,
    IdCliente int,
    Cliente nvarchar,
    Pext_Ro nvarchar,
    Folio_Roll_Pext nvarchar,
    Pext_densi nvarchar,
    Folio_densi_pext nvarchar,
    NroInterno numeric,
    IdEstado int,
    AnoGestion numeric,
    IdStatusClaro int,
    IdActualizar int,
    StatusOt nvarchar,
    StatusOt2 nvarchar,
    IdStatusOt int,
    IdStatusOt2 int,
    Folio2 nvarchar,
    IdFolio2 int,
    Capitalizacion nvarchar,
    IdStatusCj int,
    ATP nvarchar,
    PrePasivo nvarchar,
    Proyecto2 nvarchar,
    IdPapAdm int,
    IdPapTec int,
    DiasOn nvarchar,
    AntOn nvarchar
);

-- Table: Kardex
-- Columns: 29
CREATE TABLE Kardex (
    Idkardex uniqueidentifier NOT NULL DEFAULT (newid()),
    TipoMovimiento int,
    CantSap decimal,
    CodPap nvarchar,
    CantAnterior decimal,
    CantRestante decimal,
    ValorUnitario decimal,
    ValorTotal decimal,
    Referencia nvarchar,
    Almacen int,
    Observaciones nvarchar,
    Fecha date,
    Hora datetime,
    IdEmpleadoCj int,
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite int,
    TipoTrabajo nvarchar,
    Lote nvarchar,
    CantBloqueado decimal,
    UsuarioBloqueo int,
    FechaBloqueo datetime,
    NroSolicitud nvarchar,
    IdEstado int,
    PedidoSap nvarchar,
    FilaPedido int,
    FilaSolicitud int,
    Serie nvarchar
);

-- Table: Kardex_Material
-- Columns: 9
CREATE TABLE Kardex_Material (
    CodPap nvarchar NOT NULL,
    Correlativo nvarchar NOT NULL,
    CorrelaInt uniqueidentifier NOT NULL DEFAULT (newid()),
    CantSap numeric,
    Observacion nvarchar,
    CodKardex int,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime
);

-- Table: LogASignacion
-- Columns: 11
CREATE TABLE LogASignacion (
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite numeric,
    TipoTrabajo nvarchar,
    Campo nvarchar,
    Valor nvarchar,
    IdUsuario nvarchar,
    FechaCreacion datetime,
    ValorNuevo nvarchar,
    ot nvarchar
);

-- Table: LogCabLogistica
-- Columns: 22
CREATE TABLE LogCabLogistica (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    IdSolicitud nvarchar,
    ObsSolicitud nvarchar,
    Region nvarchar,
    Oc nvarchar,
    IdZona int,
    NroGuia nvarchar,
    Observacion nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Usuario nvarchar,
    IdSolicitante int,
    IdEstado int,
    OT nvarchar,
    NombreCliente nvarchar,
    NombreProyecto nvarchar,
    NombreTrabajo nvarchar
);

-- Table: LogDetLogistica
-- Columns: 20
CREATE TABLE LogDetLogistica (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    Correlativo uniqueidentifier NOT NULL DEFAULT (newid()),
    Serie nvarchar,
    CodPap nvarchar,
    CantSap numeric,
    Centro nvarchar,
    Almacen nvarchar,
    Lote nvarchar,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    IdEstado int,
    Observacion nvarchar,
    Comentario nvarchar
);

-- Table: LogOperaciones
-- Columns: 10
CREATE TABLE LogOperaciones (
    OT nvarchar,
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite numeric,
    Campo nvarchar,
    Valor nvarchar,
    IdUsuario nvarchar,
    FechaCreacion datetime,
    ValorNuevo nvarchar
);

-- Table: LogPlanilla
-- Columns: 73
CREATE TABLE LogPlanilla (
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    IdTipoTrabajo int NOT NULL,
    IdTarea int NOT NULL,
    Correlativo numeric NOT NULL,
    FecIngreso nvarchar,
    Detalle text,
    IdResponsable int,
    IdCliente int NOT NULL,
    IdBien int,
    IdComprobante int,
    RUC nvarchar,
    Serie nvarchar,
    IdTipoPago int,
    FecEmision nvarchar,
    TipoMoneda int,
    Total numeric,
    Subtotal numeric,
    IGV numeric,
    IdRendicion int,
    Observacion nvarchar,
    Comentario nvarchar,
    IdSolicitante int,
    IdGestor int,
    IdValidador int,
    IdEjecutor int,
    IdTransferencia int,
    IdBanco int,
    IdMoneda2 int,
    IdRendir int,
    FechaDeposito nvarchar,
    IdRetencion int,
    Otro nvarchar,
    Otro2 nvarchar,
    Otro3 nvarchar,
    Otro4 nvarchar,
    Estado int,
    CorreSite int,
    FechaPropuesta nvarchar,
    IdBancoCta int,
    Cuenta nvarchar,
    CuentaInter nvarchar,
    NombreCta nvarchar,
    NombreProyecto nvarchar,
    Site nvarchar,
    Tipo_Trabajo nvarchar,
    Tarea nvarchar,
    Responsable nvarchar,
    Cliente nvarchar,
    Bien nvarchar,
    Comprobante nvarchar,
    Pago nvarchar,
    Moneda nvarchar,
    Rendicion nvarchar,
    Solicitante nvarchar,
    Gestor nvarchar,
    Validador nvarchar,
    Ejecutor nvarchar,
    Transferencia nvarchar,
    Banco nvarchar,
    Moneda2 nvarchar,
    Rendir nvarchar,
    Retencion nvarchar,
    FechaAprobador nvarchar,
    Usuario nvarchar,
    FechaCreacion nvarchar,
    HoraCreacion nvarchar,
    Ot nvarchar,
    TipoPago nvarchar,
    TipoCambio numeric,
    NroFactura nvarchar,
    NroOperacion nvarchar,
    ImgFactura nvarchar
);

-- Table: Material
-- Columns: 6
CREATE TABLE Material (
    CodPap nvarchar NOT NULL,
    NombreMaterial nvarchar,
    CodEstado numeric,
    UnidadMedida nvarchar,
    FechaEliminar datetime,
    UsuarioDel nvarchar
);

-- Table: MaterialSerie
-- Columns: 10
CREATE TABLE MaterialSerie (
    CodPap nvarchar NOT NULL,
    CorrelativoInt uniqueidentifier NOT NULL DEFAULT (newid()),
    Serie nvarchar NOT NULL,
    PedidoSap nvarchar,
    IdSolicitud nvarchar,
    Correlativo nvarchar,
    IdEstado int,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime
);

-- Table: MaterialStock
-- Columns: 21
CREATE TABLE MaterialStock (
    CodPap nvarchar NOT NULL,
    Stock numeric,
    Bloqueado numeric,
    Disponible numeric,
    Solicitado numeric,
    Aprobado numeric,
    Despachado numeric,
    Enviado numeric,
    Campo numeric,
    Cruce numeric,
    Cierre numeric,
    Excedente numeric,
    Folio numeric,
    Culminadas numeric,
    Usuario int,
    Fecha date,
    Hora datetime,
    IdEstado int,
    Recepcionado numeric,
    Validado numeric,
    Observada numeric
);

-- Table: MaterialTrabajo
-- Columns: 3
CREATE TABLE MaterialTrabajo (
    CodPap nvarchar,
    TipoTrabajo nvarchar,
    IdEstado int
);

-- Table: MovEstadosPagos
-- Columns: 6
CREATE TABLE MovEstadosPagos (
    Correlativo numeric,
    Estado int,
    Observacion nvarchar,
    usuario nvarchar,
    FechaCreacion datetime,
    HoraCreacion datetime
);

-- Table: MovMaterial
-- Columns: 19
CREATE TABLE MovMaterial (
    PedidoSap nvarchar NOT NULL,
    CorrelativoInt uniqueidentifier NOT NULL DEFAULT (newid()),
    Correlativo nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    IdEstado int NOT NULL,
    Usuario nvarchar,
    Fecha datetime,
    Hora datetime,
    Observacion nvarchar,
    CodPap nvarchar,
    CantSap numeric,
    IdSolicitante int,
    NroSolicitud nvarchar,
    IdMovimiento int,
    IdCliente int,
    IdProyecto int,
    IdSite nvarchar,
    CorreSite numeric,
    TipoTrabajo nvarchar
);

-- Table: OT
-- Columns: 10
CREATE TABLE OT (
    OT nvarchar NOT NULL,
    ID nvarchar NOT NULL,
    SITE nvarchar,
    STATUS_OT nvarchar,
    CONTRATA_CONST nvarchar,
    ESTING nvarchar,
    PLANO nvarchar,
    VALMET nvarchar,
    STATUS_CW nvarchar,
    STATUS_RNI nvarchar NOT NULL
);

-- Table: PAP
-- Columns: 7
CREATE TABLE PAP (
    OcPos nvarchar,
    IdSolicitud nvarchar,
    Status_Pap nvarchar,
    Estado_Cenfile nvarchar,
    Estado_Ea nvarchar,
    Monto_Liquidado numeric,
    Estado_aprobacion nvarchar
);

-- Table: Planilla
-- Columns: 91
CREATE TABLE Planilla (
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    IdTipoTrabajo int NOT NULL,
    IdTarea int NOT NULL,
    Correlativo numeric NOT NULL,
    FecIngreso nvarchar,
    Detalle text,
    IdResponsable int,
    IdCliente int NOT NULL,
    IdBien int,
    IdComprobante int,
    RUC nvarchar,
    Serie nvarchar,
    IdTipoPago int,
    FecEmision nvarchar,
    TipoMoneda int,
    Total numeric,
    Subtotal numeric,
    IGV numeric,
    IdRendicion int,
    Observacion nvarchar,
    Comentario nvarchar,
    IdSolicitante int,
    IdGestor int,
    IdValidador int,
    IdEjecutor int,
    IdTransferencia int,
    IdBanco int,
    IdMoneda2 int,
    IdRendir int,
    FechaDeposito nvarchar,
    IdRetencion int,
    Otro nvarchar,
    Otro2 nvarchar,
    Otro3 nvarchar,
    Otro4 nvarchar,
    Estado int,
    CorreSite int,
    FechaPropuesta nvarchar,
    IdBancoCta int,
    Cuenta nvarchar,
    CuentaInter nvarchar,
    NombreCta nvarchar,
    NombreProyecto nvarchar,
    Site nvarchar,
    Tipo_Trabajo nvarchar,
    Tarea nvarchar,
    Responsable nvarchar,
    Cliente nvarchar,
    Bien nvarchar,
    Comprobante nvarchar,
    Pago nvarchar,
    Moneda nvarchar,
    Rendicion nvarchar,
    Solicitante nvarchar,
    Gestor nvarchar,
    Validador nvarchar,
    Ejecutor nvarchar,
    Transferencia nvarchar,
    Banco nvarchar,
    Moneda2 nvarchar,
    Rendir nvarchar,
    Retencion nvarchar,
    FechaAprobador nvarchar,
    Usuario nvarchar,
    FechaCreacion nvarchar,
    HoraCreacion nvarchar,
    Ot nvarchar,
    TipoPago nvarchar,
    TipoCambio numeric,
    NroFactura nvarchar,
    IdUrgente bit,
    IdReAprobador int,
    FechaReAprobador datetime,
    IdOc int,
    Fila int,
    IdTipoDoc int,
    ImgSustento nvarchar,
    ImgFactura nvarchar,
    IdUsuarioFactura int,
    FecImaFactura datetime,
    NroOperacion nvarchar,
    Cheque nvarchar,
    IdAnticipo int,
    MacAprobador nvarchar,
    MacReAprobador nvarchar,
    FechaRevision datetime,
    RevisionPm nvarchar,
    RevisionPmAprobar nvarchar,
    FechaRevisionAprobar datetime,
    MontoRetencion numeric
);

-- Table: PORTAL
-- Columns: 67
CREATE TABLE PORTAL (
    OC_POS nvarchar NOT NULL,
    IDSOLICITUD nvarchar NOT NULL,
    AREA_RESPONSABLE nvarchar,
    ACCION nvarchar,
    ANTIGUAMIENTO nvarchar,
    PENDIENTE_DE nvarchar,
    CONTRATISTA nvarchar,
    NOMBRE nvarchar,
    ESTATUS PAP nvarchar,
    TIPO_PROYECTO nvarchar,
    CODIGO_SITE nvarchar,
    NOMBRE_SITE nvarchar,
    ESTADO_SITIO nvarchar,
    F_ESTADO_SITIO date,
    ESTADO_CENFILE nvarchar,
    F_CENFILE_APRUEBA date,
    CENFILE nvarchar,
    ORDEN_COMPRA nvarchar,
    POSICION_OC nvarchar,
    FECHA_SOLICITUD date,
    SUPERVISOR_OYM_ASIGNADO nvarchar,
    FECHA_VISITA date,
    FECHA_PROGRAMACION date,
    FECHA_LISTA_PEND date,
    FECHA_EMISION_PEND date,
    FECHA_LEV_OBS date,
    FECHA_EMISION_PAC date,
    JEFE_APROBADOR nvarchar,
    FECHA_APR_JEFE date,
    GERENTE_APROBADOR nvarchar,
    FECHA_APR_GTE date,
    SUB_DIRECTOS_APROBADOR nvarchar,
    FECHA_APR_SUB_DIR date,
    FECHA_EMISION_FAC date,
    JEFE_APR_FAC nvarchar,
    FECHA_APR_JEFE_FAC date,
    GTE_APR_FAC nvarchar,
    FECHA_APR_GTE_FAC date,
    SUB_DIR_APR_FAC nvarchar,
    FECHA_APR_SUB_DIR_FAC date,
    FECHA_OBS_SOL date,
    ESTADO_EA nvarchar,
    FECHA_ENVIO_SOLICITUD date,
    FECHA_ENVIO_APROBACION date,
    ESTADO_PROYECTO nvarchar,
    OBSERVACION nvarchar,
    DETALLE_OBS_SOL nvarchar,
    ESTADO_OBS_SOL nvarchar,
    OC nvarchar,
    POSICION nvarchar,
    MONTO_OC numeric,
    MONTO_LIQUIDADO numeric,
    PORCENTAJE numeric,
    MONEDA nvarchar,
    REGION nvarchar,
    SUP_CONSTRUCCION nvarchar,
    STATUS_GIS nvarchar,
    ESTADO_APROBACION nvarchar,
    APLICA_PAC nvarchar,
    FEC_STAREGISTRO date,
    AUTO_ACEPTACION nvarchar,
    CONCEPTO nvarchar,
    Columna1 nvarchar,
    Columna2 nvarchar,
    Columna3 nvarchar,
    Columna4 nvarchar,
    Columna5 nvarchar
);

-- Table: Principal
-- Columns: 56
CREATE TABLE Principal (
    OT nvarchar NOT NULL,
    PAP nvarchar NOT NULL,
    IdSite nvarchar NOT NULL,
    Correlativo int NOT NULL,
    IdTipoTrabajo nvarchar NOT NULL,
    IdWork nvarchar NOT NULL,
    IdProyecto int,
    IdZona int,
    IdEmpleado nvarchar,
    FecAsignacion date,
    MES numeric,
    ANO numeric,
    Estado_OC nvarchar,
    Nro_Oc nvarchar NOT NULL,
    Posicion nvarchar NOT NULL,
    OcPos nvarchar NOT NULL,
    FechaOc date,
    MontoOc numeric,
    MontoLiq numeric,
    LiqPap numeric,
    ESTADO_EA nvarchar,
    FechaEa date,
    TIEMPO_EA nvarchar,
    ANTIG_EA nvarchar,
    CENFILE nvarchar,
    STATUS_GIS nvarchar,
    Status_Atp nvarchar,
    Status_Folio int,
    Comentarios nvarchar,
    IdEa int,
    GIS_SMW nvarchar,
    STATUS_PAP nvarchar,
    Status_Fact nvarchar,
    Mes2 numeric,
    Status_Cj nvarchar,
    MesActivacion numeric,
    FecActivaPap date,
    FecActivaF date,
    Status_Gerencia numeric,
    Gerencia2 numeric,
    ESTING nvarchar,
    PLANO nvarchar,
    VALMET nvarchar,
    STATUS_CW nvarchar,
    STATUS_RINI nvarchar,
    StatusClaroMod nvarchar,
    FecActMod nvarchar,
    LiqMod nvarchar,
    FolioMod nvarchar,
    Status_Claro nvarchar,
    F_act_Real nvarchar,
    FOLIO_DENSI nvarchar,
    LIQ_DENSI nvarchar,
    Status_Ro nvarchar,
    Liquidacion nvarchar,
    Ivan nvarchar
);

-- Table: Proyecto
-- Columns: 4
CREATE TABLE Proyecto (
    IdProyecto int NOT NULL,
    NombreProyecto nvarchar NOT NULL,
    FechaInicio datetime,
    Estado bit
);

-- Table: PROYECTOS_COMPLETOS
-- Columns: 422
CREATE TABLE PROYECTOS_COMPLETOS (
    OT varchar,
    ZONA varchar,
    ID_SITE varchar,
    SITE_NAME varchar,
    ESTATUS_CLARO varchar,
    DEPARTAMENTO varchar,
    FAR_END varchar,
    TRANSM_ varchar,
    PROYECTO varchar,
    TORRERA varchar,
    TIPO_TORRE varchar,
    ALTURA varchar,
    CANTIDAD_SECTORES varchar,
    LPE varchar,
    ON_AIR varchar,
    ACTA_COBERT_ varchar,
    CAPITALIZACION varchar,
    N_OC varchar,
    MONTO_S_CW varchar,
    MONTO_S_ENERGIA varchar,
    MONTO_S_PEXT varchar,
    MONTO_S_TI varchar,
    MONTO_S_ varchar,
    DATOS varchar,
    LATITUD varchar,
    LONGITUD varchar,
    DIRECCION varchar,
    CAND_VALIDADO varchar,
    CONTACTO varchar,
    TELF_ varchar,
    INGENIERÍA varchar,
    PRIORIDAD_ING varchar,
    PRIORIDAD_IMP varchar,
    ESTATUS_INGENIERIA_PEXT varchar,
    GIS_INGENIERIA varchar,
    DATA_ING_TX_CLARO varchar,
    PEXT varchar,
    DIAS_DATA varchar,
    F_DATA_ING_RX varchar,
    HILOS_ASIG varchar,
    F_SOL_ASIG_HILOS varchar,
    F_RX_ASIG_HILOS varchar,
    ID_FAREND varchar,
    FAREND_SITE_NAME varchar,
    CJ_ING_RESPONSABLE varchar,
    _DE_HILOS_HABILITAR varchar,
    PRE_DISEÑO varchar,
    CONTRATA_RESP_DISEÑO varchar,
    F_ASIG_INICIO__DISEÑO_CONTRATA varchar,
    F_LEV_CAMPO varchar,
    KMZ varchar,
    REP_FOT_DISEÑO varchar,
    PLANOS_PDF_CAD varchar,
    DIAGRAMA_DE_EMPALME varchar,
    REV_DISEÑO_CJ varchar,
    PPTO_DISEÑO varchar,
    F_DISEÑO_PEXT_ENVIADO varchar,
    TIEMPO_SIN_VAL varchar,
    F_DISEÑO_PEXT_VALIDADO varchar,
    ESTATUS_DISEÑO varchar,
    OBSERVACIONES varchar,
    METRADO_DISEÑO varchar,
    METRADO_EXISTENTE varchar,
    COD_SAP varchar,
    DESCRIPCIÓN varchar,
    TIPO_SPAM varchar,
    SOT_CID_PROY varchar,
    ESTATUS_OC varchar,
    INGENIERIA_DINAMICA varchar,
    ESTATUS_PRESUPUESTO_INTEGRAL varchar,
    RED_FLAG_PROVIAS varchar,
    ESTATUS_DISEÑO2 varchar,
    FC_INTEGRAL_CJ varchar,
    UPDATE_02_01 varchar,
    COMENTARIOS_Y_O_DEPENDENCIAS_CLARO varchar,
    SEGUIMIENTO varchar,
    CONTRATA_ING varchar,
    AVANCES varchar,
    SOLUCIÓN_ENERG_ varchar,
    POTENCIA_REQ_KW varchar,
    _CW varchar,
    _ENERG varchar,
    _PEXT varchar,
    _TI varchar,
    FECHAS_PEXT varchar,
    ESTATUS_PEXT varchar,
    PRORIDAD_PEXT varchar,
    M_FO__EXISTENTE varchar,
    M_FO__PROYECTADO varchar,
    ESTATUS_CARTA_USO_POSTES varchar,
    F_SOL_CARTA varchar,
    N_DE_POSTES_PROYECTADOS varchar,
    POSTE_EXISTENTES_ELECTRICA_BT varchar,
    POSTES_EXISTENTE_AMOV varchar,
    POSTE_EXISTENTES_ELECTRICA_MT varchar,
    TOTAL_POSTES varchar,
    TOTAL_POSTES_ELECTRICA varchar,
    CONCESIONARIA varchar,
    ESTATUS_EXP_ELECTRICO_PEXT varchar,
    ESTATUS_ELECTRICA varchar,
    N_DE_EXPEDIENTE varchar,
    FECHA_DE_ING_EXPEDIENTE varchar,
    DIAS_SIN_EXPEDIENTE2 varchar,
    JEFE_CONCESIONARIA varchar,
    GESTOR_ZONAL_RESPONSABLE varchar,
    ESTATUS_INSPECCION varchar,
    FC_INSPECCIÓN varchar,
    FECHA_INSPECCION_REAL varchar,
    RESPONSABLE_GESTION varchar,
    COMENTARIOS varchar,
    POSTES_OBSERVADOS varchar,
    POSTES_FCC_VAL varchar,
    F_VAL_FCC_ varchar,
    MUNICIPALIDAD varchar,
    EXPEDIENTE_MUNICIPAL varchar,
    F_INGRESO_EXP_MUNI varchar,
    FUIIT varchar,
    COMENTARIO_EXP_MUNICIPAL varchar,
    PMA varchar,
    CIRA varchar,
    PROVIAS varchar,
    EVAP varchar,
    SERVIDUMBRE varchar,
    ESTATUS_PERMISOS_ESPECIALES varchar,
    PERMISOS_ESPECIALES_VALIDADOS varchar,
    F_FUIIT varchar,
    F_PMA varchar,
    F_CIRA varchar,
    F_PROVIAS varchar,
    F_EVAP varchar,
    F_SERVIDUMBRE varchar,
    FC_LICENCIA varchar,
    FC_C_LICENCIA varchar,
    LICENCIA varchar,
    FIN_LICENCIA varchar,
    DÍAS_PARA_VENCIM_ varchar,
    INICIO_PEXT varchar,
    FIN_PEXT varchar,
    ESTATUS_PEXT2 varchar,
    FECHAS_CW varchar,
    ESTATUS_EJECUCION_CW varchar,
    RED_FLAG_CW varchar,
    TIPO_POSTE varchar,
    ALT_POSTE varchar,
    ESTATUS_POSTE varchar,
    FECHA_POSTE varchar,
    TRASLADO_POSTES varchar,
    FECHA_TRASLADO varchar,
    CW_PRELIMINAR varchar,
    FECHA_CW varchar,
    PARRES varchar,
    FECHA_PARRES varchar,
    PARARRAYOS varchar,
    FECHA_PARARRAYOS varchar,
    FC_PROYECTO varchar,
    FC_C_PROYECTO varchar,
    CWTS varchar,
    FC_CW_INICIADO varchar,
    FC_C_CW_INICIADO varchar,
    INICIO_CW varchar,
    FIN_CW varchar,
    FECHAS_TI varchar,
    ESTUDIO_LOS varchar,
    ENVÍO_LOS varchar,
    VALID_LOS varchar,
    RFTI varchar,
    INICIO_TI varchar,
    ENLACE_VALIDADO varchar,
    FIN_TI varchar,
    FC_OA varchar,
    FC_ACTA_COBERTURA varchar,
    FECHAS_ENERG_ varchar,
    ESTATUS_ENERGÍA varchar,
    RED_FLAG_ENERGIA varchar,
    CONCESIONARIAS varchar,
    TARIFA_REQUERIDA varchar,
    POTENCIA_REQUERIDA_WATTS_ varchar,
    POTENCIA_CONTRATADA_KW varchar,
    GESTOR varchar,
    LOCALIDAD varchar,
    ESTATUS_EXP_MUNICIPAL_AC varchar,
    F_INGRESO_EXP_AC varchar,
    T_TRANSCURRIDO_MUNI_AC varchar,
    AUTORIZACION_MUNICIPAL_AC varchar,
    COMENTARIOS2 varchar,
    EXP_ELEC_AC varchar,
    N_ATENCION varchar,
    F__INGRESO_EXPEDIENTE varchar,
    T_TRANSCURRIDO varchar,
    FACTIBILIDAD varchar,
    FECHA_FACT varchar,
    DIAS_CON_FACTIBILIDAD varchar,
    MURETE_ADEC varchar,
    F_MURETE varchar,
    METRAJE_AC__PROYECTADO varchar,
    N_DE_POSTES_PROYECTADO varchar,
    PRESUPUESTO varchar,
    CONTRATO varchar,
    MEDIDOR_O_SUMINISTRO varchar,
    TABLERO varchar,
    FC_ENERGIZADO varchar,
    ACCIONES_A_TOMAR varchar,
    FC_ENERGÍA_PROVISIONAL varchar,
    INICIO_ENERGÍA varchar,
    FIN_ENERGÍA varchar,
    ENERGÍA_OK varchar,
    COMENTARIOS_AC varchar,
    W42 varchar,
    W43 varchar,
    W44 varchar,
    W45 varchar,
    W46 varchar,
    W47 varchar,
    W48 varchar,
    W49 varchar,
    W50 varchar,
    W51 varchar,
    W52 varchar,
    W53 varchar,
    W54 varchar,
    W55 varchar,
    W56 varchar,
    W57 varchar,
    W58 varchar,
    W59 varchar,
    W60 varchar,
    W61 varchar,
    W62 varchar,
    W63 varchar,
    W64 varchar,
    W65 varchar,
    W66 varchar,
    W67 varchar,
    W68 varchar,
    W69 varchar,
    W70 varchar,
    W71 varchar,
    W2_W1 varchar,
    IMP_PEXT varchar,
    ESTATUS_EJECUCION_PEXT varchar,
    RED_FLAG_PEXT varchar,
    ESTATUS_PERMISOS varchar,
    VIABILIDAD varchar,
    ESTADO_HW varchar,
    F_SOL_FO varchar,
    F_ASIG_FO varchar,
    F_PAP_FO varchar,
    F_RX_FO varchar,
    _DIAS_ENTREGA_FO varchar,
    CODIGO varchar,
    DESCRIPTIONS varchar,
    SPAM varchar,
    METRAJE_SOLICITADO varchar,
    SOT_CID varchar,
    COD_POSTE varchar,
    STATUS_DATA_PEXT varchar,
    POSTES_FV_09 varchar,
    POSTES_FV_11 varchar,
    ESTATUS_POSTES_FV varchar,
    POSTES_CAC_09 varchar,
    POSTES_CAC_11 varchar,
    ESTATUS_POSTES_CAC varchar,
    TOTAL_POSTES_FINAL varchar,
    ESTATUS_POSTES_GENERAL varchar,
    ANALISTA_PEXT varchar,
    CONTRATA_PEXT varchar,
    F_INIC_EJEC varchar,
    F_FIN_PEXT varchar,
    W_PEXT_EJEC varchar,
    POSTES varchar,
    TENDIDO varchar,
    FUSIONES varchar,
    PINT varchar,
    ACABADOS varchar,
    _DE_HILOS_INSTALADOS varchar,
    METRAJE_INSTALADO varchar,
    PRIORIDAD varchar,
    SEGUIMIENTO_PEXT varchar,
    FÓRMULAS varchar,
    VISITA_DE_CANDIDATOS varchar,
    ENVÍO_DE_SAR varchar,
    FIRMA_DE_CONTRATO varchar,
    INGRESO_DE_CONTRATO varchar,
    OTENCIÓN_CIRA varchar,
    OTENCIÓN_PMA varchar,
    OTENCIÓN_DIA varchar,
    OTENCIÓN_DGAC varchar,
    INGRESO_LICENCIA varchar,
    REALIZAR_LOS varchar,
    EJECUCIÓN_EMS varchar,
    EJECUCIÓN_EMS_FE varchar,
    RELEVAMIENTO_DE_TORRE varchar,
    ENVÍO_PROYECTO varchar,
    INICIO_DE_CW varchar,
    LISTO_PARA_EQUIPOS varchar,
    FIN_DE_CW varchar,
    IMP_TI varchar,
    ESTATUS_EJECUCION_TI varchar,
    RED_FLAG_TI varchar,
    TECNOLOGÍA varchar,
    MODELO_ANTENA varchar,
    CANTIDAD_SECTORES2 varchar,
    TIPO varchar,
    ESTADO_HW_TI varchar,
    F_SOL_RF varchar,
    F_ASIG_RF varchar,
    F_PAP_RF varchar,
    F_RX_RF varchar,
    _DIAS_ENTREGA_RF varchar,
    DF_4G varchar,
    WOTX varchar,
    SCRIPT varchar,
    FO_PINT varchar,
    SOPORTES_RF varchar,
    CONTRATA_TI varchar,
    F_ACT_REAL varchar,
    W_ACT_REAL varchar,
    PUESTA_EN_SERVICIO varchar,
    ENVÍO_ACTA_COBERTURA varchar,
    FECHA_ACTA_COBERTURA varchar,
    CAPITALIZACIÓN varchar,
    PRIORIDAD_TI varchar,
    SEGUIMIENTO_TI varchar,
    FÓRMULAS_ENERGÍA varchar,
    SOLICITAR_FACTIBILIDAD varchar,
    OBTENER_FACTIBILIDAD varchar,
    SOLICITAR_PUNTO_DISEÑO varchar,
    OBTENER_PUNTO_DISEÑO varchar,
    INGRESO_PROY_CONCESIONARIA varchar,
    INICIO_OBRAS_ENERGÍA varchar,
    FIN_OBRAS_ENERGÍA varchar,
    INSTALACIÓN_SUMINISTRO varchar,
    FORECAST_CLARO varchar,
    FC_GENERAL varchar,
    WEEK_ACTIVACION varchar,
    PROY_ varchar,
    PRIORIDAD_CLARO varchar,
    OT_PAP2 varchar,
    IdZona int,
    IdSite nvarchar,
    CorreSite numeric,
    Status_Claro int,
    IdDepartamento int,
    IdTransmision int,
    IdProyecto int,
    IdTorrera int,
    IdTipoTorre int,
    IdOnAir int,
    IdActaCob int,
    IdCapitalizacion int,
    IdCandado int,
    IdContacto int,
    IdStatusIng int,
    GIS_INGENIERIA2 int,
    DATA_ING_TX_CLARO2 int,
    HILOS_ASIG2 int,
    AnalistaIng int,
    idContrataResp int,
    KMZ2 int,
    REP_FOT_DISEno int,
    IdPlanosPdf int,
    IdDiagramaEmpalme int,
    PptoDise int,
    Status_Diseno int,
    ESTATUS_OC2 int,
    IdIngDinamica int,
    PreInt int,
    RED_FLAG_PROVIAS2 int,
    StatusPext int,
    PriPext int,
    StatusCartaPoste int,
    CONCESIONARIA2 int,
    StatusExpPext int,
    IdStatusElectrica int,
    IdJefeConcesionaria int,
    IdGestorZonal int,
    ESTATUS_INSPECCION2 int,
    IdRespGestion int,
    IdExpMun int,
    MUNICIPALIDAD2 int,
    FUIIT2 int,
    PMA2 int,
    CIRA2 int,
    PROVIAS2 int,
    EVAP2 int,
    SERVIDUMBRE2 int,
    StatPermEspe int,
    PermEspecial int,
    StatusEjecCw int,
    TipoPoste int,
    AlturaPoste int,
    StatusPoste int,
    TrasladoPoste int,
    CwPreliminar int,
    Parres2 int,
    Pararrayos2 int,
    StatusEjecTi int,
    Tecnologia int,
    ModAntena int,
    Tipo2 int,
    EstHwTi int,
    Df int,
    WOTX2 int,
    SCRIPT2 int,
    FO_PINT2 int,
    SOPORTES_RF2 int,
    CONTRATA_TI2 int,
    PtaServ int,
    EnvActCob int,
    Capitalizacion2 int,
    PRIORIDAD_TI2 int,
    StatusEnergia int,
    CONCESIONARIAS2 int,
    IdGestorEne int,
    IdLocalidad int,
    EstExpMunPal int,
    idFact int,
    MureteAdec int,
    IdPresupuestado int,
    IdContrato int,
    IdSuministro int,
    IdTablero int
);

-- Table: SeguimientoMulta
-- Columns: 8
CREATE TABLE SeguimientoMulta (
    IdMulta numeric,
    ContaSeg int,
    FecSeg date,
    TxtSeg nvarchar,
    TxtImagen nvarchar,
    Usuario nvarchar,
    FechaCreacion date,
    HoraCreacion datetime
);

-- Table: Site
-- Columns: 4
CREATE TABLE Site (
    IdSite nvarchar NOT NULL,
    NombreSite nvarchar NOT NULL,
    IdZona int NOT NULL,
    Correlativo int NOT NULL
);

-- Table: SolicitudEnvio
-- Columns: 24
CREATE TABLE SolicitudEnvio (
    IdCliente int NOT NULL,
    IdProyecto int NOT NULL,
    IdSite nvarchar NOT NULL,
    CorreSite numeric NOT NULL,
    TipoTrabajo nvarchar NOT NULL,
    PedidoSap nvarchar NOT NULL,
    NroSolicitud nvarchar NOT NULL,
    Descripcion nvarchar,
    FechaEnvio datetime,
    HoraEnvio datetime,
    NroGuia nvarchar,
    IdAgencia int,
    NombreAgencia nvarchar,
    Monto numeric,
    IdResponsable int,
    FechaEntrega datetime,
    FechaEnviado datetime,
    Aplica int,
    FechaRecojo datetime,
    Imagen nvarchar,
    IdEstado int,
    FechaCreacion datetime,
    HoraCreacion datetime,
    Usuario nvarchar
);

-- Table: sysdiagrams
-- Columns: 5
CREATE TABLE sysdiagrams (
    name nvarchar NOT NULL,
    principal_id int NOT NULL,
    diagram_id int NOT NULL,
    version int,
    definition varbinary
);

-- Table: Ubigeo
-- Columns: 2
CREATE TABLE Ubigeo (
    CodUbigeo nvarchar,
    NombreUbigeo nvarchar
);

-- Table: UpdImportar
-- Columns: 10
CREATE TABLE UpdImportar (
    Ot nvarchar,
    Cliente nvarchar,
    Proyecto nvarchar,
    IdSite nvarchar,
    TipoTrabajo nvarchar,
    AnoGestion numeric,
    Fecha datetime,
    Hora datetime,
    IdActualizar int,
    Site nvarchar
);

-- Table: Usuario
-- Columns: 7
CREATE TABLE Usuario (
    Id int NOT NULL,
    IdUsuario nvarchar NOT NULL,
    Clave nvarchar,
    IdEstado int,
    IdEmpleado int,
    IdCargo int,
    NombreDispositivo nvarchar
);

-- Table: vAreaUpd
-- Columns: 2
CREATE TABLE vAreaUpd (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vBeneficio
-- Columns: 9
CREATE TABLE vBeneficio (
    IdBeneficio numeric,
    NombreEmpleado nvarchar,
    NroDocumento nvarchar,
    Monto numeric,
    Expr1 numeric,
    MesPago nvarchar,
    IdEmpleadoCj int,
    NombreCliente nvarchar,
    Aprobador nvarchar
);

-- Table: vCampoUpd
-- Columns: 2
CREATE TABLE vCampoUpd (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vClienteUpd
-- Columns: 2
CREATE TABLE vClienteUpd (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEmpresaUpd
-- Columns: 2
CREATE TABLE vEmpresaUpd (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: Version
-- Columns: 4
CREATE TABLE Version (
    IdVersion int NOT NULL,
    NombreVersion nvarchar,
    FechaCreacion nvarchar,
    Estado bit
);

-- Table: vEstadoAsistencia
-- Columns: 2
CREATE TABLE vEstadoAsistencia (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadoCierre
-- Columns: 2
CREATE TABLE vEstadoCierre (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadoCruce
-- Columns: 2
CREATE TABLE vEstadoCruce (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadoDespacho
-- Columns: 2
CREATE TABLE vEstadoDespacho (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadoFolio
-- Columns: 2
CREATE TABLE vEstadoFolio (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadoRecepcion
-- Columns: 2
CREATE TABLE vEstadoRecepcion (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadosSalida
-- Columns: 2
CREATE TABLE vEstadosSalida (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadoValidar
-- Columns: 2
CREATE TABLE vEstadoValidar (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vEstadpCampo
-- Columns: 2
CREATE TABLE vEstadpCampo (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vSerie
-- Columns: 1
CREATE TABLE vSerie (
    Serie nvarchar
);

-- Table: vTransferencia
-- Columns: 2
CREATE TABLE vTransferencia (
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL
);

-- Table: vUbicacionUpd
-- Columns: 7
CREATE TABLE vUbicacionUpd (
    Sociedad nvarchar NOT NULL,
    Programa nvarchar NOT NULL,
    Campo nvarchar NOT NULL,
    Correlativo int NOT NULL,
    ValorIni nvarchar NOT NULL,
    ValorFin nvarchar NOT NULL,
    Detalle nvarchar
);

-- Table: vVacaciones
-- Columns: 13
CREATE TABLE vVacaciones (
    IdEmpleadoCj int,
    NombreEmpleado nvarchar,
    FechaInicio date,
    FechaFin date,
    IdEstado int,
    Estado nvarchar,
    IdEmpRel int,
    NroDocumento nvarchar,
    IdClienteCj int,
    NombreCliente nvarchar,
    PreAprobador nvarchar,
    PrimAprobador nvarchar,
    Autorizado nvarchar
);

